### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alejandro-falkowski-gelato** [Nerzal/gocloak#100]
**Describe the bug**
Not checking nil

**To Reproduce**
Issue is here https://github.com/Nerzal/gocloak/blob/master/client.go#L245

The code:

```go
usedKey := findUsedKey(decodedHeader.Kid, certResult.Keys)
token, err := jwx.DecodeAccessTokenCustomClaims(accessToken, usedKey.E, usedKey.N, claims)
```

`usedKey` is not checked for nil.

It should be:

```go
usedKey := findUsedKey(decodedHeader.Kid, certResult.Keys)
if usedKey == nil {
  return nil, errors.New("cannot find a key to decode the token")
}

return  jwx.DecodeAccessTokenCustomClaims(accessToken, usedKey.E, usedKey.N, claims)
```

**Expected behavior**
Not to crash with a panic

**Comment by SVilgelm** [comment]
Could you make a PR? I like your solution and will approve it

**Comment by alejandro-falkowski-gelato** [comment]
@SVilgelm - Created a PR.

**Comment by Nerzal** [comment]
PR is merged. Thank u

**Comment by alejandro-falkowski-gelato** [comment]
Please advise when this will be released in version 3?

**Comment by SVilgelm** [comment]
Done - v3.5.2: https://github.com/Nerzal/gocloak/releases/tag/v3.5.2
