### ISSUE TITLE
Keycloak token introspection always fails with {“active”:false}

### ISSUE THREAD

**Issue by asatelier** [Nerzal/gocloak#106]
**Describe the bug**
Testing the introspection to know if the token is in active state, it always gives false.
If there is another way to prove this, please describe it.

**To Reproduce**

```
	client := gocloak.NewClient(url)
	token, err := client.Login("account", client_secret, realm,username,password)
	if err != nil {
		panic("Login failed:"+ err.Error())
	}

	rptResult, err := client.RetrospectToken(token.AccessToken, client_id, client_secret, realm)
	if err != nil {
		panic("Inspection failed:"+ err.Error())
	}

	if !rptResult.Active {
		panic("Token is not active")
	}
```

**Expected behavior**
It should return token information and its active status

```
{"exp":1574658355,"iat":1574656555,"aud":aud,"active":true,"jti":jti,"typ":typ}
```

**Additional context**
Keycloak Version < 4.8 (gopkg.in/nerzal/gocloak.v1)

Investigating I found that the solution is to add the following data in the message body: client_id, client_secret, username.

```
// RetrospectToken calls the openid-connect introspect endpoint
func (client *gocloak) RetrospectToken(accessToken string, clientID, clientSecret string, realm string,username string) (*RetrospecTokenResult, error) {
	var result RetrospecTokenResult
	resp, err := getRequestWithBasicAuth(clientID, clientSecret).
		SetFormData(map[string]string{
			"client_id":     clientID,
			"client_secret": clientSecret,
			"username": username,
			"token":           accessToken,
		}).
		SetResult(&result).
		Post(client.basePath + authRealms + realm + tokenEndpoint + "/introspect")
	err = checkForError(resp, err)
	if err != nil {
		return nil, err
	}

	return &result, nil
}
```

**Comment by SVilgelm** [comment]
Seems, you are right, it was fixed later, when i implemented `GetToken` function, it sets those fields. Could you backport this function? https://github.com/Nerzal/gocloak/blob/master/client.go#L258

unfortunately, i don't have a time now to work on gocloak

**Comment by SVilgelm** [comment]
BTW Did you try the v3 with that keycloak?

**Comment by SVilgelm** [comment]
I  did run the tests gains Keycloak v4.7.0.
There is only one failed test due to not matching error message.
The test for the RetrospectToken function is passed: https://travis-ci.com/Nerzal/gocloak/jobs/260282066#L11146

I think you just need to use lates version of gocloak

**Comment by SVilgelm** [comment]
Here is a travis build with testing current code against some of the old versions of the keycloak: https://travis-ci.com/Nerzal/gocloak/builds/138167632

**Comment by asatelier** [comment]
Hi, I tried using v3 but I can't download the library. I use "dep" to download the libraries and I get the following error:

`
Solving failure: No versions of gopkg.in/nerzal/gocloak.v3 met constraints:
	v3.7.0: Could not introduce gopkg.in/nerzal/gocloak.v3@v3.7.0, as it requires package github.com/Nerzal/gocloak/v3/pkg/jwx from github.com/Nerzal/gocloak, but in version v2.1.0 that package is missing.
	v3.6.0: Could not introduce gopkg.in/nerzal/gocloak.v3@v3.6.0, as it requires package github.com/Nerzal/gocloak/v3/pkg/jwx from github.com/Nerzal/gocloak, but in version v2.1.0 that package is missing.
	v3.5.2: Could not introduce gopkg.in/nerzal/gocloak.v3@v3.5.2, as it requires package github.com/Nerzal/gocloak/v3/pkg/jwx from github.com/Nerzal/gocloak, but in version v2.1.0 that package is missing.
	v3.5.1: Could not introduce gopkg.in/nerzal/gocloak.v3@v3.5.1, as it requires package github.com/Nerzal/gocloak/v3/pkg/jwx from github.com/Nerzal/gocloak, but in version v2.1.0 that package is missing.
	v3.5.0: Could not introduce gopkg.in/nerzal/gocloak.v3@v3.5.0, as it requires package github.com/Nerzal/gocloak/v3/pkg/jwx from github.com/Nerzal/gocloak, but in version v2.1.0 that package is missing.
	v3.4.0: Could not introduce gopkg.in/nerzal/gocloak.v3@v3.4.0, as it requires package github.com/Nerzal/gocloak/v3/pkg/jwx from github.com/Nerzal/gocloak, but in version v2.1.0 that package is missing.
	v3.3.0: Could not introduce gopkg.in/nerzal/gocloak.v3@v3.3.0, as it requires package github.com/Nerzal/gocloak/v3/pkg/jwx from github.com/Nerzal/gocloak, but in version v2.1.0 that package is missing.
	v3.2.0: Could not introduce gopkg.in/nerzal/gocloak.v3@v3.2.0, as it requires package github.com/Nerzal/gocloak/v3/pkg/jwx from github.com/Nerzal/gocloak, but in version v2.1.0 that package is missing.
	v3.1.0: Could not introduce gopkg.in/nerzal/gocloak.v3@v3.1.0, as it requires package github.com/Nerzal/gocloak/v3/pkg/jwx from github.com/Nerzal/gocloak, but in version v2.1.0 that package is missing.
	v3.0.0: Could not introduce gopkg.in/nerzal/gocloak.v3@v3.0.0, as it requires package github.com/Nerzal/gocloak/v3/pkg/jwx from github.com/Nerzal/gocloak, but in version v2.1.0 that package is missing.

`

Download v2 and call getToken, this worked fine, but RetrospectToken still doesn't work.

I want to get if a token is valid or not.

Tanks for your time.

Also try the following:
`
go get gopkg.in/nerzal/gocloak.v3
`

And I got the error:
`
package github.com/Nerzal/gocloak/v3/pkg/jwx: cannot find package "github.com/Nerzal/gocloak/v3/pkg/jwx" in any of:
        /usr/local/Cellar/go/1.10.1/libexec/src/github.com/Nerzal/gocloak/v3/pkg/jwx (from $GOROOT)
        /Users/user/go/src/github.com/Nerzal/gocloak/v3/pkg/jwx (from $GOPATH)
package github.com/go-resty/resty/v2: cannot find package "github.com/go-resty/resty/v2" in any of:
        /usr/local/Cellar/go/1.10.1/libexec/src/github.com/go-resty/resty/v2 (from $GOROOT)
        /Users/user/go/src/github.com/go-resty/resty/v2 (from $GOPATH)

`

**Comment by SVilgelm** [comment]
Just ‘go get github.com/Nerzal/gocloak/v3‘

**Comment by SVilgelm** [comment]
Here is a issue how to use dep to download latest version https://github.com/Nerzal/gocloak/issues/85

**Comment by SVilgelm** [comment]
the current code also works with v4.6.0 and v4.5.0: https://travis-ci.com/Nerzal/gocloak/builds/138277292
v4.4.0 and less are not able to import a realm, so it requires to change the unit tests.
@asatelier what Keycloak version do you use?

**Comment by SVilgelm** [comment]
So, can I close the issue?

**Comment by asatelier** [comment]
Hi, I was using version 3.5. But download a docker with version 8.

I was able to download v3 from the library and connect it to the local keycloak (in docker).

I did the tests and they worked well, I was able to get a token, I was also able to inspect the token, and it returned me active: true.

Thank you very much for answering.

**Comment by SVilgelm** [comment]
Ok, closing the issue
