### ISSUE TITLE
It would be nice if CreateGroup returned the created group's id

### ISSUE THREAD

**Issue by agorman** [Nerzal/gocloak#110]
I'd like the signature of CreateGroup to change from

`CreateGroup(accessToken string, realm string, group Group) error`

to

`CreateGroup(accessToken string, realm string, group Group) (string, error)`

This would match the signature of CreateUser which already returns a user id. I'd be happy to write a pull request for this but I wanted to run it by you first because I'm not sure if it's okay to change the interface of an existing method.

Thanks!

**Comment by SVilgelm** [comment]
I’m ok with this

**Comment by SVilgelm** [comment]
It would be better, if you can do it for all functions, what creates any object.
Realm, user, role, group. What else?

**Comment by SVilgelm** [comment]
+client

**Comment by SVilgelm** [comment]
+scope

**Comment by agorman** [comment]
Wow, I was going to take a look at this but looks like you already did it. :thumbsup:

**Comment by SVilgelm** [comment]
Yeah, i have a free time

**Comment by SVilgelm** [comment]
But, since the patch breaks a backward compatibility i decided to finish work with pointers (#79), so the v4 will contain changes for IDs and pointers.
