### ISSUE TITLE
fatal error: concurrent map writes (client.GetCerts())

### ISSUE THREAD

**Issue by chrnin** [Nerzal/gocloak#118]
Hi, 

Lately, I experienced some crashes with gocloak involving the client.GetCerts (client.go) function.
I took a look to this function to understand why and I think I have a solid explaination.

This function tests if certs are present in client.certsLock. If they're present, it returns the map, end of the game. If they're not, the function fetch them with client.getNewCerts(realm) and writes them to client.certsCache. After that a goroutine waits a given delay and deletes the old certs.

When a customer comes back after that, certs are missing and the function manages to get new ones... Good game, but…

When a customer comes back at the exact moment the timer goes on certs deletion, 2 map read/writes occurs at the same moment and crash the whole process.

I'll send a PR in minutes to fix that using a Mutex to protect client.certsCache read and writes.

Have a good day :)

**Comment by SVilgelm** [comment]
Fixed by #119

**Comment by SVilgelm** [comment]
Released in v4.2.0: https://github.com/Nerzal/gocloak/releases/tag/v4.2.0
