### ISSUE TITLE
Use APIError

### ISSUE THREAD

**Issue by agorman** [Nerzal/gocloak#132]
**Is your feature request related to a problem? Please describe.**
It would be nice to get the status code returned from Keycloak.

**Describe the solution you'd like**
Return APIErrors from gocloak calls. This could be tricky for errors resulting from things other than Keycloak API calls.

**Describe alternatives you've considered**
Can't think of any though I'm totally open to any existing solutions I'm unaware of.

**Additional context**
I have my own HTTP service in front of gocloak and right now it's hard to determine what errors and response codes I should return. For example I might get an error back like this "400 Bad Request: Password policy not met. See logs for details".

I'd like to be able to set my response code to 400 and set an appropriate error of "Password policy not met." The "See logs for details" part doesn't really make sense but I'm not sure there is anything that can be done to solve that.

**Comment by SVilgelm** [comment]
Do you mean anything special by APIError? Any libraries or interfaces?

**Comment by Nerzal** [comment]
I could imagine using something like this when returning errors

``` golang
// APIError holds message and statusCode for api errors
type APIError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Detail  string `json:"detail,omitempty"`
}

// Error stringifies the APIError
func (apiError APIError) Error() string {
	return "Code: " + strconv.Itoa(apiError.Code) + "Message: " + apiError.Message + "Detail: " + apiError.Detail
}
```

**Comment by Nerzal** [comment]
When improving the error handling, we could also use error wrapping. In order to provide better errors, that are way more helpful when searching for problems.

My favorite package for error wrapping is: 
https://github.com/pkg/errors

I stole the error wrapping stuff from dave cheney and i'm using it everywhere. Makes life easier.
https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully

**Comment by agorman** [comment]
I was actually just referring to the `APIError` struct that already exists. Though I like Nerzal's improvement above.

https://github.com/Nerzal/gocloak/blob/master/models.go#L58

Error wrapping is also now standard library as of go 1.13. Not sure if you want to make that a requirement though.

https://blog.golang.org/go1.13-errors

**Comment by Nerzal** [comment]
@SVilgelm what do you think?
We could just pack the information inside an APIError object inside the checkForErrors method and return this as error. 

Optional (Additionaly):
We could wrap the errors to provide even better error handling

**Comment by SVilgelm** [comment]
wrapping errors means adding additional restrictions of go 1.13, am I right?
I would prefer to use wrapping, due to better handling

**Comment by Nerzal** [comment]
we don't have to restrict to go 1.13 if we use the pkg/errors lib for that. 
It is the better implementation, also dave chaney contributed to it (must be good) :D

**Comment by SVilgelm** [comment]
Ok, let's do it :)

**Comment by Nerzal** [comment]
i'll do that. shouldn't take long
