### ISSUE TITLE
Feature RememberMe handle by REST API

### ISSUE THREAD

**Issue by jvaca92** [Nerzal/gocloak#135]
**Feature RememberMe handle by REST API**
I try to find way how can be handle feature RememberMe by REST API. Actually I cannot find API which will provide this kind feature. The remember me can be managed just by login page of the Keycloak if I am not wrong.

**Solution**
Would be great if the login method which is responsible for to login user also provide boolean parameter for rememberMe. But also should be exist some API from the Keycloak side.

**Comment by SVilgelm** [comment]
The `gocloak` is a just library, it's a wrapper for Keycloak REST API and such functionality cannot be done by `gocloak`. Because it should not store the tokens, this can lead to security problems.

If you need such functionality you should implement it by yourself. Just store tokens somewhere, I did it by marshaling the tokens structure to a file and unmarhsalling before do a request:

```go
// Unmarshal reads a token from a file
func (t *Token) Unmarshal(filename string) *Token {
	data, err := ioutil.ReadFile(filename)
	if err == nil {
		_ = json.Unmarshal(data, t)
		log.Debugf("Token has been loaded from file: %s", filename)
		log.Tracef("Token: %+v", t)
	} else {
		log.Debugf("Unable to load a token from the file '%s': %+v", filename, err)
	}
	return t
}

// Marshal writes a token to a file
func (t *Token) Marshal(filename string) *Token {
	data, err := json.Marshal(t)
	if err != nil {
		log.Fatalf("Unable to marshal a token: %v", err)
	}
	err = ioutil.WriteFile(filename, data, 0600)
	if err != nil {
		log.Fatalf("Unable to save a token to the file '%s': %v", filename, err)
	}
	log.Debugf("Token has been saved to the file: '%s'", filename)
	return t
}
```

**Comment by SVilgelm** [comment]
Or if you are using a browser then you can configure the Keycloak login's page to remember you, but it is not related to gocloak library.

**Comment by jvaca92** [comment]
So lets say that in Keycloak I will setup the expiration of the token for specific client to infinity and then the expiration will be handled by Redis. Actually the handling the expiration of the tokens is much easier in Redis. So the workflow I imagine like that:

Login user -> Use gocloak to recieve JWT token ->  If the login is success then store token in Redis and if remeberme is true, then setup inifinity expiration if not then setup default expiration which will be defined by user in configuration of the app. 

Bearer token validaton -> Let that we have some auth service which verify if the token exist. The verification will be done trought the service which use some Redis client and check if the token is still valid or not.

Logout user -> when user do the logout action then token will be done through the gocloak which provide API for logout. If the logout is successful then remove the token from the Redis

This is just my use case how I would implement the logic for rememberme. If someone have any idea how could be improved the workflow then would appreciate any comments

**Comment by SVilgelm** [comment]
> So lets say that in Keycloak I will setup the expiration of the token for specific client to infinity and then the expiration will be handled by Redis
It is an offline token.

The workflow should be a bit different:
1. If remember me: Login user -> Use gocloak to recieve offline JWT token -> Store it in Redis -> Always use refresh (in this case offline) token to get an acmes token -> Use access token to do a work
2. If no remember me:  Login user -> Use gocloak to recieve offline JWT token -> store the Refresh Token in Redis -> same as above ^^^^

**Comment by jvaca92** [comment]
You right. Thanks for correction.  Actually lifespan of the token can be handled just for the whole realm and no for specific client.

**Comment by Nerzal** [comment]
@jvaca92 you can change the lifetime of an access token for specific clients:

![grafik](https://user-images.githubusercontent.com/9110370/73127580-b02a7800-3fc2-11ea-8376-0fffd56b65ef.png)
