### ISSUE TITLE
Missing method UpdateClientProtocolMapper

### ISSUE THREAD

**Issue by tingeltangelthomas** [Nerzal/gocloak#137]
Currently there is no method to update a client protocol mapper.
I expect a method like UpdateClientProtocolMapper.

Update the mapper as documented in keycloak docu (https://www.keycloak.org/docs-api/5.0/rest-api/index.html)
PUT  /{realm}/clients/{id}/protocol-mappers/models/{id}

Kind Regards 
Thomas

**Comment by SVilgelm** [comment]
Hi, thank you so much for the request, but I think it would be faster, if you can provide a pull request.

**Comment by tingeltangelthomas** [comment]
Hi, thanks @SVilgelm I've created https://github.com/Nerzal/gocloak/pull/138.

**Comment by Nerzal** [comment]
merged.

**Comment by Nerzal** [comment]
and thank u <3
