### ISSUE TITLE
Check compatibility with KeyCloak 9.0.0

### ISSUE THREAD

**Issue by Nerzal** [Nerzal/gocloak#147]
New KeyCloak major version is released. 

We should check, if we are still compatible.

https://www.keycloak.org/2020/02/keycloak-900-released.html

**Comment by SVilgelm** [comment]
easy peasy :)

**Comment by SVilgelm** [comment]
@Nerzal actually It work fine, there are some broken unit tests, I don't understand why they fail, but in general the v9 works and they fixed the problem we had with 8.2

**Comment by Nerzal** [comment]
so we can close this issue?
