### ISSUE TITLE
client skip checking connection SSL

### ISSUE THREAD

**Issue by lazywhite** [Nerzal/gocloak#149]
**Is your feature request related to a problem? Please describe.**
```
client := gocloak.NewClient(serverURL)
token, err := client.LoginClient(clientID, clientSecretKey, realmName)

error: 
Post https://<domain>auth/auth/realms/avlcloud/protocol/openid-connect/token: x509: certificate signed by unknown authority

```

**Describe the solution you'd like**
add last argument "false", to skip checking connection ssl
```
 token, err := client.LoginClient(clientID, clientSecretKey, realmName, false)
```
like this python code
```
from keycloak import KeycloakOpenID
keycloak_openid = KeycloakOpenID(server_url=SERVER_URL,
                    client_id=CLIENT_ID,
                    realm_name=REALM_NAME,
                    client_secret_key=CLIENT_SECRET_KEY,
                    verify=False)
```

**Comment by Nerzal** [comment]
I'd rather implement that as functional options when instantiating the keycloak client instead of adding this as a parameter in the method

**Comment by lazywhite** [comment]
I made a change for NewClient, look this
```
https://github.com/lazywhite/gocloak/blob/master/client.go#L111
```

but now it give me this error
```
404 Not Found
```

**Comment by SVilgelm** [comment]
No no no no,
```go
client := gocloak.NewClient(serverURL)
restyClient := client.RestyClient()
restyClient.SetTLSClientConfig(&tls.Config{ InsecureSkipVerify: true })
```

**Comment by SVilgelm** [comment]
please use `client.RestyClient()` to configure anything you need

**Comment by lazywhite** [comment]
```
    client := gocloak.NewClient(serverURL)
    restyClient := client.RestyClient()
    restyClient.SetTLSClientConfig(&tls.Config{ InsecureSkipVerify: true })

    token, err := client.LoginClient(clientID, clientSecretKey, realmName)
    fmt.Println(token)
    fmt.Println(err.Error())

```
now it still give me this error
```
<nil>
404 Not Found

```

**Comment by SVilgelm** [comment]
But it is another problem m, seems you have an incorrect url

**Comment by lazywhite** [comment]
same server_url,  before this change , error looks like this 
```
Post https://<domain>auth/auth/realms/avlcloud/protocol/openid-connect/token: x509: certificate signed by unknown authority
```
after change, it's 404
python-keycloak client works fine on this server_url

I'm on #goclock  slack channel now

**Comment by SVilgelm** [comment]
it's another problem, ssl validations happens on another level. First it does the SSL validation for the `<domain>auth` domain. If it's pass then it send a request to by this url and key cloak returns 404. In README.md you can find, the the urls should be `https://<keycloak domain>` and nothin else, it shouldn't;t contain full url to the token endpoint. You can also enable debug mode to see all requests and responses:

```go
restyClient.client.SetDebug(true)
```

**Comment by lazywhite** [comment]
check this debug output
https://gist.github.com/lazywhite/1621ed8995f0970a63074aa15f7eb4c4

**Comment by SVilgelm** [comment]
`auth` is present twice in the url: `/auth/auth/realms/avlcloud/protocol/openid-connect/token`

**Comment by lazywhite** [comment]
you mean it's a problem of nginx  proxy?  what do you think can fix this

**Comment by SVilgelm** [comment]
It's a problem in your keycloak url, in your very first message I see that it tries to request a token by url: `https://<domain>auth/auth....`
double `auth`
Probably you need to remove first `auth` from your keycloak url and it should be: `https://<domain>`

**Comment by lazywhite** [comment]
It is weired, python client works fine, but after I remove the /auth, it give me this errorhttps://gist.github.com/lazywhite/5db84dabbc7072c7705927556c2a1e39

**Comment by SVilgelm** [comment]
Maybe because it's not a python client? This library has completely different interface. I never heard about that python library. So we did not take into account any python libraries when implemented this one.

Talking about your issue:
```
{
   "error": "unauthorized_client",
   "error_description": "Invalid client secret"
}
```

I think it's clear, you need to provide a correct secret

**Comment by lazywhite** [comment]
but python client works fine by using the same client_id and client_secret,  
what's the problem?

**Comment by SVilgelm** [comment]
What keycloak's version do you use?
I really cannot say anything here, since I have no idea how it's configured.
Maybe we have an error in `LoginClient` function, but the tests works fine:

```go
	token, err := client.LoginClient(
		cfg.GoCloak.ClientID,
		cfg.GoCloak.ClientSecret,
		cfg.GoCloak.Realm)
```

**Comment by SVilgelm** [comment]
Could you show you python code? Maybe you missed something?

**Comment by lazywhite** [comment]
https://gist.github.com/lazywhite/a41875dc40003f770badaee8fc5def79

**Comment by SVilgelm** [comment]
Thanks, I see. 
The function ` keycloak_openid.userinfo()` takes a token as a parameter, you have that token in the `Authorization` variable.
How did you get that token?
I'm asking ti because the `client.LoginClient()` returns a token, like it does the `token` function in  `python-keycloak`:
```# Get Token
token = keycloak_openid.token("user", "password")
token = keycloak_openid.token("user", "password", totp="012345")
```

**Comment by lazywhite** [comment]
this is go code 
https://gist.github.com/lazywhite/55c3251c0dba6e7c53ca4f06970cf9a2

I got that Authorization var from html page, after I login that website

**Comment by SVilgelm** [comment]
So, then you don't need to call the `LoginClient` function, since you are already have the token.

Here is the code you probably need:
```go
serverURL := os.Getenv("SERVER_URL")  // no auth in the url!!!
token := os.Getenv("Authorization")
realmName := os.Getenv("REALM_NAME")

client := gocloak.NewClient(serverURL)
userInfo, err := client.GetUserInfo(token, realmName)
fmt.Println(userInfo)
```

**Comment by lazywhite** [comment]
thx a lot! you saved my life. maybe you can put this in README, show how to skip SSL check
```
    client := gocloak.NewClient(serverURL)
    restyClient := client.RestyClient()
    restyClient.SetDebug(true)
    restyClient.SetTLSClientConfig(&tls.Config{ InsecureSkipVerify: true })
```

**Comment by SVilgelm** [comment]
Sure, we we'll add it

**Comment by Nerzal** [comment]
I just added it to the readme
