### ISSUE TITLE
clientID is not that  id by keycloak

### ISSUE THREAD

**Issue by zengzhengrong** [Nerzal/gocloak#151]
gocloak version v5
keycloak verison 9.0.0

Every clientID argument is a uuid , not keycloak Client ID

My kaycloak Manage page show me Client ID is ```app```,and that app url is 
```
<hostname>/auth/admin/master/console/#/realms/demo/clients/8bb0f130-a60e-4575-a6fb-56d3bc2f85e2
```
```
8bb0f130-a60e-4575-a6fb-56d3bc2f85e2
```
is a ```clientID ``` for argument ,
If I input app to clientID , It's 404
```
404 Not Found: Client not found
```
So, I consider it's not friendly

**Comment by SVilgelm** [comment]
I'm a bit confused, where do you input `app`, in a web browser or in a go code using gocloak?

**Comment by zengzhengrong** [comment]
```
roles, err := client.GetClientRoles(token.AccessToken, realm, "8bb0f130-a60e-4575-a6fb-56d3bc2f85e2")
```
it ok
```
roles, err := client.GetClientRoles(token.AccessToken, realm, "app")
```
it 404

**Comment by SVilgelm** [comment]
Ok, so it's the Keycloak's behavior, we cannot change anything here.
You can do something like this:
```go
clientID := "app"
clients, err := client.GetClients(
  token.AccessToken,
  cfg.GoCloak.Realm,
  GetClientsParams{
    ClientID: &clientID,
})
roles, err := client.GetClientRoles(token.AccessToken, realm, clients[0].ID)
```

**Comment by zengzhengrong** [comment]
Got it , thank so much

**Comment by SVilgelm** [comment]
We are trying to not do any special magic in the library, like ^^^^

But If you have a time and wish, feel free to open a PR with new function using ClientID instead of client.

It sounds very useful, but I don't have a time to implement it.
