### ISSUE TITLE
APIError as return type

### ISSUE THREAD

**Issue by jvaca92** [Nerzal/gocloak#152]
**Describe the bug**
I see that from v5 is possible get more detail error as APIError but not sure how get from functions which are implemented in client because each function return standard error.

**Expected behavior**
Expected APIError as return type for every client function

**Comment by Nerzal** [comment]
I tried to Cover every method that calls keycloak with these APIErrors.

I currently don't really know what information could be used to enrich the information in the remaining methods.

**Comment by jvaca92** [comment]
In some cases the response status will be really useful such as when username is not found or the password is incorrect. In classic error the response status is just defined in error message.

**Comment by mweibel** [comment]
Standard error handling in Go can do this, e.g.:
```
	switch err := err.(type) {
	case *gocloak.APIError:
		// now you have access to APIError
	}
```

There are other methods to achieve it, read up on go error handling for that.

**Comment by Nerzal** [comment]
I guess this can be closed by now :)
