### ISSUE TITLE
Variable Resources in PolicyRepresentation is always null

### ISSUE THREAD

**Issue by jvaca92** [Nerzal/gocloak#156]
**Issue description**

When I call method GetPolicies am I getting all existing policies for my realm and client but when I try to access variable Resources in PolicyRepresentation I am getting always null and the resources exist because I have created them through admin ui. 
Can be problem with mapping of the resources ?  

**Expecting behavior**
Able to get resources through PolicyRepresentation.

**Comment by SVilgelm** [comment]
Hi, Could you show your code? How do you query the policies?
Unfortunately I cannot find a good documentation for resource-server API, so I cannot validate that we have a correct representation. But I found at least one error here: https://github.com/Nerzal/gocloak/blob/master/client.go#L1999

Here is Pr to fix that issue: https://github.com/Nerzal/gocloak/pull/157

**Comment by SVilgelm** [comment]
The PR #157 is merged and released in https://github.com/Nerzal/gocloak/releases/tag/v5.0.1

**Comment by SVilgelm** [comment]
Please check with new version

**Comment by SVilgelm** [comment]
@jvaca92 i'm closing this issue due to not responding. Feel free to re-open is necessary
