### ISSUE TITLE
Get User Credentials API

### ISSUE THREAD

**Issue by grizzly-monkey** [Nerzal/gocloak#158]
**Is your feature request related to a problem? Please describe.**
Current there is no API to get user credentials

**Describe the solution you'd like**
API to get user credentials.

**Additional context**
<img width="1390" alt="Screenshot 2020-03-21 at 1 58 05 AM" src="https://user-images.githubusercontent.com/6825834/77204043-e80ff080-6b17-11ea-9917-56422881c83a.png">

```
curl 'https://SERVER/auth/admin/realms/{REALM}/users/{USERID}/credentials' 
```
RESPONSE:
```json
[{"id":"12296c78-b9ad-4ef4-a272-e801f8ae44a6","type":"password","createdDate":1584731908202,"credentialData":"{\"hashIterations\":27500,\"algorithm\":\"pbkdf2-sha256\"}"}]

**Comment by SVilgelm** [comment]
Hi,
feel free to raise a PR with this feature
