### ISSUE TITLE
Manage federated identities of an user

### ISSUE THREAD

**Issue by awltr** [Nerzal/gocloak#160]
**Is your feature request related to a problem? Please describe.**
No api to manage federated identity of an user (maybe I'm missing something)

**Describe the solution you'd like**
Functions for the following calls
- GET /{realm}/users/{id}/federated-identity
- POST /{realm}/users/{id}/federated-identity/{provider}
- DELETE /{realm}/users/{id}/federated-identity/{provider}

**Describe alternatives you've considered**
I implement it myself. Unfortunately, there are also some supporting functions in gocloak private, which would make this a bit easier

**Comment by SVilgelm** [comment]
Yeah, you are right, we didn't implement these APIs, but we are open for the new PRs.

**Comment by SVilgelm** [comment]
Release in v5.1.0: https://github.com/Nerzal/gocloak/releases/tag/v5.1.0
