### ISSUE TITLE
Custom attributes not included in GetUserInfo method

### ISSUE THREAD

**Issue by ydstaana** [Nerzal/gocloak#173]
The UserInfo struct does not include any custom attributes

[https://github.com/Nerzal/gocloak/blob/master/models.go#L548](url)

**Comment by SVilgelm** [comment]
It would be faster if you can create a PR with needed changes.

**Comment by SVilgelm** [comment]
@ydstaana Please review the #183, I extended the UserInfo structure with all standard claims and added GetRawUserInfo function that returns `map[string]interface{}` if you need custom claims

**Comment by AlexisZankowitch** [comment]
Sorry for digging up an old thread but I didn't find the information elsewhere and since it's related to custom attributes:

Is there a possibility with gocloak to query for users using a custom attribute?
