### ISSUE TITLE
Can't reset RequiredActions for users because of omitempty flag

### ISSUE THREAD

**Issue by evgeniy-scherbina** [Nerzal/gocloak#174]
Hello,

I want to reset RequiredActions for user, but if I set RequiredActions to empty slice and call UpdateUser(user) method - keycloak simply ignore it.

I found out that it because of `omitempty` flag for RequiredActions in user struct.

This code fails to reset actions
```
user, err := client.GetUserByID(token.AccessToken, realm, userID)
if err != nil { ... }

user.RequiredActions = []string{}

err = client.UpdateUser(token.AccessToken, realm, *user)
if err != nil { ... }
```

**Comment by SVilgelm** [comment]
seems we also should use pointers for the arrays to fix this

**Comment by SVilgelm** [comment]
@Nerzal @alexsn @viniciussousazup @agorman 
Guys, you all use this library. I want to discuss with you about a proper solution for this bug.
First solution that I came up with is changing all arrays to pointers, like:
```go
<<<<<
RequiredActions            []string
>>>>
RequiredActions            *[]string
```

But I really don't like it. Maybe you have any thoughts?

The problem here, the `omitempty` tag removes the empty array, but we also cannot remove `omitempty` tag because in this case any UserUpdate calls will change this field to empty.

**Comment by alexsn** [comment]
Unfortunately that's how json encoder works and it doesn't differentiate between an empty slice and a nil slice in the presence of  `omitempty` tag.

Possible alternatives:
- We can change RequiredActions to `interface{} `which does differentiate between nil and empty string slice as you expect (see [here](https://play.golang.org/p/yalEqHhO6k4) as a playground sample) but we loose type safety.
- We can define our own type as `type StringSlice interface{}` and implement `json.Marshaler` that will do the required type checks during runtime via reflection.

Both of those are worst than what you're suggesting above. I suggest we also add a `StringSliceP` helpers to simplify `*[]string` creation.

**Comment by SVilgelm** [comment]
but the problem is much worse, we need to change all array types in the all models and implement `json.Marshaler` for all new types

**Comment by alexsn** [comment]
No no, just use `*[]string` with `omitempty` for fields where we need to differentiate between an empty slice and undefined.

**Comment by agorman** [comment]
I can live with `*[]string`. It's a pretty simple change for code using the library and won't be a breaking change for those not directly using those fields. It also matches the previous change to make fields pointers for the same reason.

**Comment by Nerzal** [comment]
> Unfortunately that's how json encoder works and it doesn't differentiate between an empty slice and a nil slice in the presence of `omitempty` tag.
> 
> Possible alternatives:
> 
>     * We can change RequiredActions to `interface{} `which does differentiate between nil and empty string slice as you expect (see [here](https://play.golang.org/p/yalEqHhO6k4) as a playground sample) but we loose type safety.
> 
>     * We can define our own type as `type StringSlice interface{}` and implement `json.Marshaler` that will do the required type checks during runtime via reflection.
> 
> 
> Both of those are worst than what you're suggesting above. I suggest we also add a `StringSliceP` helpers to simplify `*[]string` creation.

Losing type safety is not an option here. 
Having a *[]string is kinda annoying, but i have no other solution right now

**Comment by SVilgelm** [comment]
Here is what I'm talking about:
```diff
diff --git a/models.go b/models.go
index 5e30415..69f422b 100644
--- a/models.go
+++ b/models.go
@@ -127,14 +127,14 @@ type User struct {
        LastName                   *string                     `json:"lastName,omitempty"`
        Email                      *string                     `json:"email,omitempty"`
        FederationLink             *string                     `json:"federationLink,omitempty"`
-       Attributes                 map[string][]string         `json:"attributes,omitempty"`
-       DisableableCredentialTypes []interface{}               `json:"disableableCredentialTypes,omitempty"`
-       RequiredActions            []string                    `json:"requiredActions,omitempty"`
-       Access                     map[string]bool             `json:"access"`
-       ClientRoles                map[string][]string         `json:"clientRoles,omitempty"`
-       RealmRoles                 []string                    `json:"realmRoles,omitempty"`
+       Attributes                 *map[string][]string         `json:"attributes,omitempty"`
+       DisableableCredentialTypes *[]interface{}               `json:"disableableCredentialTypes,omitempty"`
+       RequiredActions            *[]string                    `json:"requiredActions,omitempty"`
+       Access                     *map[string]bool             `json:"access"`
+       ClientRoles                *map[string][]string         `json:"clientRoles,omitempty"`
+       RealmRoles                 *[]string                    `json:"realmRoles,omitempty"`
        ServiceAccountClientID     *string                     `json:"serviceAccountClientId,omitempty"`
-       Credentials                []*CredentialRepresentation `json:"credentials,omitempty"`
+       Credentials                *[]*CredentialRepresentation `json:"credentials,omitempty"`
 }
```

and same for all other model

**Comment by SVilgelm** [comment]
Please review the #182 
@Nerzal ^

**Comment by SVilgelm** [comment]
Fixed and released in v6: https://github.com/Nerzal/gocloak/releases/tag/v6.0.0
