### ISSUE TITLE
Adding context.Context support to GoCloak interface

### ISSUE THREAD

**Issue by alexsn** [Nerzal/gocloak#179]
**Is your feature request related to a problem? Please describe.**
It's not possible to pass `context.Context` to underlying resty request. 

**Describe the solution you'd like**
All `GoCloak` methods sending HTTP requests should take `context.Context` as first argument (e.g. `GetToken(ctx context.Context, realm string, options TokenOptions) (*JWT, error)`). This is a backwards incompatible change and will require a `v6` version bump. 

**Describe alternatives you've considered**
All `GoCloak` interface methods can be duplicated to add `context.Context`, meaning we'll have `GetTokenContext` in addition to `GetToken` where the latter will pass `context.Background()` to the former.

**Comment by alexsn** [comment]
I can implement either approach, just let me know what's preferred (if any).

**Comment by SVilgelm** [comment]
I'm ok with first approach, we need to bump v6 because of #176

**Comment by SVilgelm** [comment]
Released in v6: https://github.com/Nerzal/gocloak/releases/tag/v6.0.0
