### ISSUE TITLE
Logout all sessions for a user

### ISSUE THREAD

**Issue by ydstaana** [Nerzal/gocloak#185]
Keycloak Admin UI provides this functionality to logout all sessions for a user

POST /{realm}/users/{id}/logout for Keycloak REST

i'd like to open a PR for this. I can't seem to open a pull request

**Comment by Nerzal** [comment]
Everyone should be able to open a PR. 
So what is the problem, when you try to open a PR ? :)

**Comment by ydstaana** [comment]
remote: Permission to Nerzal/gocloak.git denied to ydstaana.
fatal: unable to access 'https://github.com/Nerzal/gocloak.git/': The requested URL returned error: 403

**Comment by Nerzal** [comment]
Did you fork the repository prior to this? 
As you need your own copy of this repo, do the changes their and then you can pullrequest the changes into this repository

See https://gist.github.com/Chaser324/ce0505fbed06b947d962 for reference :)

**Comment by ydstaana** [comment]
Thanks! I've opened https://github.com/Nerzal/gocloak/pull/186

**Comment by SVilgelm** [comment]
Released in v6.3.0
