### ISSUE TITLE
Provide flexibility to drop "/auth" from realm URLs

### ISSUE THREAD

**Issue by surajbarkale** [Nerzal/gocloak#191]
It is possible configure Keycloak to have URL in the form `https://auth.example.com/realms/Users` instead of `https://example.com/auth/realms/Users`. However, this library only allows the second form.

The "/auth/" is hardcoded in client.go:
https://github.com/Nerzal/gocloak/blob/c0de0212f8f48f8e1f08fa047d876ee2760100b2/client.go#L36

Can you please provide this flexibility?

**Comment by Nerzal** [comment]
It might be possible to add a client configuration, that could omit this, but in before implementing such a feature, i'd like to understand why you need this change. 

Do you have a keycloak that is configured to listen to urls like in your first example?

**Comment by surajbarkale** [comment]
Yes. I have this configuration deployed in production.

**Comment by Nerzal** [comment]
Okay, i try to find time this weekend to provide a fix. 
It isn't a big deal to change this and it should be possible without a breaking change.
