### ISSUE TITLE
Implement the "remove a specific user session" api

### ISSUE THREAD

**Issue by eduardev** [Nerzal/gocloak#193]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the `DELETE /{realm}/sessions/{session} ` call implemented so we could remove a specific user session. This is to circumvent the lack of session limiting in keycloak (https://issues.redhat.com/browse/KEYCLOAK-849)

**Describe the solution you'd like**
Implement the API call.

**Describe alternatives you've considered**
There's none as I cannot kill all sessions if I don't have an access token. On login, if I want to guarantee single session per user, I would have to:

1. login
2. kill all session with my new token
3. login again 

**Additional context**
N/A

**Comment by SVilgelm** [comment]
Hi,
Would you be able to create a PR? Looks like it's very simple.

**Comment by eduardev** [comment]
I will
I just need to figure out where do I get the session id, I guess it's the `session_state` in the response.

**Comment by SVilgelm** [comment]
@eduardev you can use [GetUserSessions](https://github.com/Nerzal/gocloak/blob/master/client.go#L1755) function

**Comment by eduardev** [comment]
@SVilgelm thanks... you are right, but that's out of scope of gocloak itself. Just implemented the endpoint calling. It's up the the lib user to decide strategy.

**Comment by SVilgelm** [comment]
Released in `v6.4.0`
