### ISSUE TITLE
unable to install Nerzal / gocloak package 

### ISSUE THREAD

**Issue by BalamuruganP25** [Nerzal/gocloak#200]
**Describe the bug**
we can't able to check out the package Nerzal / gocloak package  using "go get" comments 
(Note - previously working fine now days we are getting problem )

**To Reproduce**
go get -u  github.com/Nerzal/gocloak

error 
package github.com/dgrijalva/jwt-go/v4: cannot find package "github.com/dgrijalva/jwt-go/v4" in any of:
    /usr/local/go/src/github.com/dgrijalva/jwt-go/v4 (from $GOROOT)
    /root/Goprojects/src/github.com/dgrijalva/jwt-go/v4 (from $GOPATH)

**Screenshots**
![bug_git](https://user-images.githubusercontent.com/50692411/89863844-93553b00-dbc8-11ea-9e36-1820324d8b6a.PNG)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version:18.04

**Comment by Nerzal** [comment]
Hi, 

what happens, when you do 

> GO111MODULES=on go get -u -v github.com/Nerzal/gocloak/v6

**Comment by BalamuruganP25** [comment]
today morning i try to install new gocloak package . i got error so i raise the issues request please help me . i try new comment i'm getting below result. 
![bug_git_1](https://user-images.githubusercontent.com/50692411/89886720-bb559600-dbea-11ea-9c04-0b958e19fd40.PNG)

**Comment by Nerzal** [comment]
I just wanted to know if you are using gomodules. 
I have not tried to use gocloak without gomodules. 

But that log looks good, a bit short to short, but good. 
What go version are u using? 
For go1.13 and above GO111Module is more or less enabled by default

**Comment by BalamuruganP25** [comment]
yes i'm using go module .. 

version - go1.13.5 linux/amd64

**Comment by BalamuruganP25** [comment]
i found something in your code ... your code fetching  below package 
github.com/dgrijalva/jwt-go/v4
but not in git hub ...

**Comment by SVilgelm** [comment]
Everything work fine, I use go14, but it also should work on go13:
```shell
20-08-11 10:22 % mkdir tmp
20-08-11 10:22 % cd tmp
20-08-11 10:23 % go mod init tmp                    
go: creating new go.mod: module tmp
20-08-11 10:23 % go get github.com/Nerzal/gocloak/v7
go: downloading github.com/Nerzal/gocloak/v7 v7.1.0
go: github.com/Nerzal/gocloak/v7 upgrade => v7.1.0
```

Same for v6 with `-u` flag:
```shell
20-08-11 10:24 % go mod init tmp                    
go: creating new go.mod: module tmp
20-08-11 10:24 % go get -u github.com/Nerzal/gocloak/v6
go: downloading github.com/Nerzal/gocloak/v6 v6.4.0
go: github.com/Nerzal/gocloak/v6 upgrade => v6.4.0
go: github.com/segmentio/ksuid upgrade => v1.0.3
go: golang.org/x/net upgrade => v0.0.0-20200707034311-ab3426394381
```

**Comment by SVilgelm** [comment]
also `v7` of gocloak uses `v4` of `jwt-go` everywhere, if you see an error, could you provide a link for the code? Because I cannot find anything wrong

**Comment by narenswamy** [comment]
hello,

i am also getting same error...can u please look it on..

**Comment by narenswamy** [comment]
Hello,

i am trying to install github.com/Nerzal/gocloak, i am getting same error.

/Goprojects/src/github.com#  go get github.com/Nerzal/gocloak
package github.com/dgrijalva/jwt-go/v4: cannot find package "github.com/dgrijalva/jwt-go/v4" in any of:
    /usr/local/go/src/github.com/dgrijalva/jwt-go/v4 (from $GOROOT)
    /root/Goprojects/src/github.com/dgrijalva/jwt-go/v4 (from $GOPATH)

1.unable to get  below package from github.

github.com/dgrijalva/jwt-go/v4 ---> not found 404 error.
![error](https://user-images.githubusercontent.com/24434847/89979458-70408f00-dc8d-11ea-89ed-6541fd9779aa.PNG)

**Comment by SVilgelm** [comment]
Please read how the go modules work. You need to use versions suffix: `go get github.com/Nerzal/gocloak/v7` in case of gocloak it is `v7`

**Comment by SVilgelm** [comment]
If you want to open the project on github, then you don't need the suffix: github.com/dgrijalva/jwt-go

**Comment by BalamuruganP25** [comment]
i don't want github.com/dgrijalva/jwt-go package.
i want only gocloak package.
but  gocloak  use github.com/dgrijalva/jwt-go/v4  package . while installing  gocloak   package is automatically  fetching github.com/dgrijalva/jwt-go/v4 package. 

did u try gocloak   package . (NOTE - with proper golang environment)?
we are  facing  the issues  on july 27 2020  still is continue. 

plz try & fresh  install gocloak   package with proper golang environment

**Comment by SVilgelm** [comment]
You cannot install `gocloak` without `jwt-go`, otherwise it will not work. The `gocloak` uses the `jwt-go` to work with `jwt` tokens, so you need it anyway.

Could you please repeat next steps and share the logs here?:
1. `mkdir tmp`
2. `cd tmp`
3. `go mod init tmp`
4. `go get github.com/Nerzal/gocloak/v7`

I just tested it yesterday with proper Golang environment and it works as expected.

**Comment by BalamuruganP25** [comment]
Thanks buddy .. working find .. we use common Repo so we facing issues . now working fine ..
