### ISSUE TITLE
dep init failing

### ISSUE THREAD

**Issue by knasim** [Nerzal/gocloak#213]
dep init
init failed: unable to solve the dependency graph: Solving failure: No versions of github.com/Nerzal/gocloak met constraints:
        v7.4.0: Could not introduce github.com/Nerzal/gocloak@v7.4.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v7.3.0: Could not introduce github.com/Nerzal/gocloak@v7.3.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v7.2.0: Could not introduce github.com/Nerzal/gocloak@v7.2.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v7.1.0: Could not introduce github.com/Nerzal/gocloak@v7.1.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v7.0.2: Could not introduce github.com/Nerzal/gocloak@v7.0.2, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v7.0.1: Could not introduce github.com/Nerzal/gocloak@v7.0.1, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v7.0.0: Could not introduce github.com/Nerzal/gocloak@v7.0.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v6.4.0: Could not introduce github.com/Nerzal/gocloak@v6.4.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v6.3.3: Could not introduce github.com/Nerzal/gocloak@v6.3.3, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v6.3.2: Could not introduce github.com/Nerzal/gocloak@v6.3.2, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v6.3.1: Could not introduce github.com/Nerzal/gocloak@v6.3.1, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v6.3.0: Could not introduce github.com/Nerzal/gocloak@v6.3.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v6.2.0: Could not introduce github.com/Nerzal/gocloak@v6.2.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v6.1.0: Could not introduce github.com/Nerzal/gocloak@v6.1.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v6.0.0: Could not introduce github.com/Nerzal/gocloak@v6.0.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v5.5.0: Could not introduce github.com/Nerzal/gocloak@v5.5.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v5.4.0: Could not introduce github.com/Nerzal/gocloak@v5.4.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v5.3.0: Could not introduce github.com/Nerzal/gocloak@v5.3.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v5.2.1: Could not introduce github.com/Nerzal/gocloak@v5.2.1, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v5.2.0: Could not introduce github.com/Nerzal/gocloak@v5.2.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v5.1.0: Could not introduce github.com/Nerzal/gocloak@v5.1.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v5.0.1: Could not introduce github.com/Nerzal/gocloak@v5.0.1, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v5.0.0: Could not introduce github.com/Nerzal/gocloak@v5.0.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v4.8.0: Could not introduce github.com/Nerzal/gocloak@v4.8.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v4.7.0: Could not introduce github.com/Nerzal/gocloak@v4.7.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v4.6.0: Could not introduce github.com/Nerzal/gocloak@v4.6.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v4.5.0: Could not introduce github.com/Nerzal/gocloak@v4.5.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v4.4.0: Could not introduce github.com/Nerzal/gocloak@v4.4.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v4.3.1: Could not introduce github.com/Nerzal/gocloak@v4.3.1, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v4.3.0: Could not introduce github.com/Nerzal/gocloak@v4.3.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v4.2.0: Could not introduce github.com/Nerzal/gocloak@v4.2.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v4.1.0: Could not introduce github.com/Nerzal/gocloak@v4.1.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v4.0.0: Could not introduce github.com/Nerzal/gocloak@v4.0.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.10.0: Could not introduce github.com/Nerzal/gocloak@v3.10.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.9.0: Could not introduce github.com/Nerzal/gocloak@v3.9.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.8.0: Could not introduce github.com/Nerzal/gocloak@v3.8.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.7.0: Could not introduce github.com/Nerzal/gocloak@v3.7.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.6.0: Could not introduce github.com/Nerzal/gocloak@v3.6.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.5.2: Could not introduce github.com/Nerzal/gocloak@v3.5.2, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.5.1: Could not introduce github.com/Nerzal/gocloak@v3.5.1, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.5.0: Could not introduce github.com/Nerzal/gocloak@v3.5.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.4.0: Could not introduce github.com/Nerzal/gocloak@v3.4.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.3.0: Could not introduce github.com/Nerzal/gocloak@v3.3.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.2.0: Could not introduce github.com/Nerzal/gocloak@v3.2.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.1.0: Could not introduce github.com/Nerzal/gocloak@v3.1.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.0.1: Could not introduce github.com/Nerzal/gocloak@v3.0.1, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3.0.0: Could not introduce github.com/Nerzal/gocloak@v3.0.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v2.1.0: Could not introduce github.com/Nerzal/gocloak@v2.1.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v2.0.1: Could not introduce github.com/Nerzal/gocloak@v2.0.1, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v2.0.0: Could not introduce github.com/Nerzal/gocloak@v2.0.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v1.0.0: Could not introduce github.com/Nerzal/gocloak@v1.0.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        master: Could not introduce github.com/Nerzal/gocloak@master, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        gh-pages: Could not introduce github.com/Nerzal/gocloak@gh-pages, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v1.0: Could not introduce github.com/Nerzal/gocloak@v1.0, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v2: Could not introduce github.com/Nerzal/gocloak@v2, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v3: Could not introduce github.com/Nerzal/gocloak@v3, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v4: Could not introduce github.com/Nerzal/gocloak@v4, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v5: Could not introduce github.com/Nerzal/gocloak@v5, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)
        v6: Could not introduce github.com/Nerzal/gocloak@v6, as its subpackage github.com/Nerzal/gocloak/v7 is missing. (Package is required by (root).)

**Comment by SVilgelm** [comment]
The `gocloak` library support go modules
to install it please use command `go get github.com/Nerzal/gocloak/v7` and import it as `import "github.com/Nerzal/gocloak/v7"`

**Comment by Nerzal** [comment]
To be honest, i did never test gocloak with dep, as dep can be considered deprecated, as go modules is replacing it.

The dep readme states: 

```
dep was initially developed to experiment with a new dependency management system for Go; but, as of Go 1.11, the Go project has officially adopted a different approach, based on the concept of Modules, which is described in a series of posts published on blog.golang.org.
```

That is why we won't bring in much effort to support dep.

**Comment by knasim** [comment]
> To be honest, i did never test gocloak with dep, as dep can be considered deprecated, as go modules is replacing it.
> 
> The dep readme states:
> 
> ```
> dep was initially developed to experiment with a new dependency management system for Go; but, as of Go 1.11, the Go project has officially adopted a different approach, based on the concept of Modules, which is described in a series of posts published on blog.golang.org.
> ```
> 
> That is why we won't bring in much effort to support dep.


Okay, good to know. Thanks.
