### ISSUE TITLE
Attributes role is nil

### ISSUE THREAD

**Issue by trallka** [Nerzal/gocloak#216]
**Describe the bug**
Role attributes are not returned.
Role attributes by methods are not returned:
roles, err := client.GetRealmRolesByUserID(ctx, token.AccessToken, realm, userID)
roles, err := client.GetClientRolesByUserID(ctx , token.AccessToken, realm, clientID, userID)

All these methods return nil for attributes...

In keycloak, all roles are created and assigned to the user. All attributes of the roles are respectively prescribed too.
The attributes of the roles are also visible in the database and in the keycloak interface.

**To Reproduce**
host := "host" 
realm := "master" 
clientID := "clientID"
clientSecret := "clientSecret"
userID := "userID"

client := gocloak.NewClient(host)

ctx := context.Background()

token, err := client.LoginAdmin(ctx, "admin", "pass", realm)
				
roles, err := client.GetClientRolesByUserID(ctx , token.AccessToken, realm, clientID, userID)
				
for i, role := range roles {

  fmt.Println(i, ">>>>>>>>>>>>>> role.ID: ", gocloak.PString(role.ID))
  fmt.Println(i, ">>>>>>>>>>>>>> role.Name: ", gocloak.PString(role.Name))
  fmt.Println(i, ">>>>>>>>>>>>>> role.ScopeParamRequired: ", role.ScopeParamRequired)
  fmt.Println(i, ">>>>>>>>>>>>>> role.Composite: ", role.Composite)
  fmt.Println(i, ">>>>>>>>>>>>>> role.Composites: ", role.Composites)
  fmt.Println(i, ">>>>>>>>>>>>>> role.ClientRole: ", role.ClientRole)
  fmt.Println(i, ">>>>>>>>>>>>>> role.ContainerID: ", gocloak.PString(role.ContainerID))
  fmt.Println(i, ">>>>>>>>>>>>>> role.Description: ", gocloak.PString(role.Description))
  fmt.Println(i, ">>>>>>>>>>>>>> role.Attributes: ", role.Attributes)
						
}

**Expected behavior**
map[string][]string for attributes should be returned. Not nil when attributes is exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/68782951/91837403-ddc05980-ec54-11ea-8122-5925ac583b0b.png)
![image](https://user-images.githubusercontent.com/68782951/91842916-8c689800-ec5d-11ea-8b55-13d469b026dc.png)
![image](https://user-images.githubusercontent.com/68782951/91842996-a904d000-ec5d-11ea-9a02-210b45ee3f3d.png)

Keycloak version — 11.0.1
Keycloak DB_VENDOR — POSTGRES
import "github.com/Nerzal/gocloak/v7"

**Comment by trallka** [comment]
uma_role, err := client.**GetClientRole**(ctx, token.AccessToken, realm, clientID, "uma_protection")

If take the role directly, you can get the attributes. The question is closed.
![image](https://user-images.githubusercontent.com/68782951/93780515-f064f780-fc30-11ea-954d-a11d8c91f88e.png)

**Comment by HarikrishnanBalagopal** [comment]
Hi, I don't think this should be closed. Please provide the attributes when getting all the roles instead of forcing us to do an extra set of requests in a for loop.

**Comment by HarikrishnanBalagopal** [comment]
Another Update:
This endpoint (Get effective client-level role mappings This recurses any composite roles)
```
GET /{realm}/users/{id}/role-mappings/clients/{client}/composite
```
DOES provide the option to get the role attributes if you provide a query parameter `briefRepresentation`
![image](https://user-images.githubusercontent.com/20921177/133243889-24fe0c62-ba4c-47ad-bfe7-e0f467b1bc40.png)

This endpoint is exposed as `GetCompositeClientRolesByUserID` in this `GoCloak` library
However that function does not expose the option to add the query parameter.

# Related
The Java library does expose the query parameter:
https://stackoverflow.com/questions/63116643/keycloak-can-not-get-attributes-of-a-role
