### ISSUE TITLE
Wrong Protection API endpoint

### ISSUE THREAD

**Issue by anonrig** [Nerzal/gocloak#217]
**Describe the bug**
It appears that according to 11.0.2 the UMA compliant url for protection api is:

```
http://${host}:${port}/auth/realms/${realm_name}/authz/protection/resource_set
```

The existing implementation from december 2019, refers to a really old version from 4.X of Keycloak, and I don't really quite understand how the tests does pass.

The correct documentation is https://www.keycloak.org/docs/latest/authorization_services/#creating-a-resource

**Comment by anonrig** [comment]
@Nerzal I wanted to tag you (to grab your attention other than Github's actual notification ahah), since this is an important task for us. If this is an issue, and I didn't miss anything, I can open a PR to fix it asap.

**Comment by SVilgelm** [comment]
@anonrig Hi, thank you for pointing it our. Will you be able to create a Pull Request with needed changes?

**Comment by anonrig** [comment]
It appears that it's not as simple as changing the endpoint for permission api. The parameters are also wrong. I'll be opening a pr, but it appears that the whole code refers to an old version of keycloak. (referring this assumption based on gocloak's reference to `resource-server` endpoint, where keycloak 11 API doesn't have any endpoint that includes a keyword `resource-server`

**Comment by anonrig** [comment]
I'm referring to the documentation from https://www.keycloak.org/docs/latest/authorization_services/#_service_protection_resources_api where UMA-compliant  endpoint is 

```
http://${host}:${port}/auth/realms/${realm_name}/authz/protection/resource_set
```

**Comment by SVilgelm** [comment]
But how the Resources tests are working now?

**Comment by anonrig** [comment]
that's what i've failed to understand, and it's the million dollar question

**Comment by SVilgelm** [comment]
seems, they did not delete the endpoints, kind of deprecated

**Comment by sachinjohar2** [comment]
Is there any PR for this? I can contribute as I need to use new protection APIs without using the admin token.

**Comment by timdrysdale** [comment]
@sachinjohar2 check out new methods for this in [PR #233](https://github.com/Nerzal/gocloak/pull/233)

**Comment by Nerzal** [comment]
I guess this can be closed now :)
