### ISSUE TITLE
GetUsers not return User.RealmRoles and User.Groups

### ISSUE THREAD

**Issue by marcomoscatelli** [Nerzal/gocloak#224]
**Describe the bug**
The resulted User structure not have User.RealmRoles and User.Groups

**To Reproduce**
1. Create a keycloak confidential client
2. use gocloak.GetUsers methods
3. print result ([]*User)

**Expected behavior**
User structure have User.RealmRoles and User.Groups

**Versions:**
 - gocloak/v7
 - Keycloak 11.0.2

**Additional context**
as additional question: what is the correct mode to write the GetUsersParams.Search string?

Thanks

**Comment by Anubiso** [comment]
This could be a problem in keycloak itself as it doesn't return these infos in the REST-Response:
https://stackoverflow.com/questions/48458138/keycloak-user-roles-missing-in-rest-api

**Comment by ianare** [comment]
I did something like this if it's of any help to others:

```
type completeUserInfo struct {
	user *gocloak.UserInfo
	groups []*gocloak.Group
}

func (c *keycloakConnection) GetUserInfo(userToken string) (*completeUserInfo, error) {
	user, err := c.client.GetUserInfo(c.ctx, userToken, c.params.Realm)
	if err != nil {
		return nil, err
	}
	log.Print(user)
	userInfo := &completeUserInfo{
		user: user,
	}
	params := gocloak.GetGroupsParams{}
	groups, err := c.client.GetUserGroups(c.ctx, c.token.AccessToken, c.params.Realm, *user.Sub, params)
	if err == nil {
		log.Print(groups)
		userInfo.groups = groups
	}
	return userInfo, nil
}
```
