### ISSUE TITLE
Adding a mock of GoCloak interface? 

### ISSUE THREAD

**Issue by akoserwal** [Nerzal/gocloak#232]
**Is your feature request related to a problem? Please describe.**
It would be good to have a gocloak mock interface added to the library. It will help to consume the library and add supporting unit test cases without spinning up a keycloak instance

**Describe the solution you'd like**
Using the library: `https://github.com/matryer/moq`
it will be easier to generate and add to the repo.

**Comment by SVilgelm** [comment]
I think it's not a good idea to store the mock in this repository, so people are using different libraries for mocking, like gomock, mockgen, mod and etc...
For example I have never used moq, I prefer gomock or mockgen, so the mocks generated by moq will be useless to me. You can easily keep it in your repository
