### ISSUE TITLE
README.md invalid Create User example 

### ISSUE THREAD

**Issue by exu** [Nerzal/gocloak#237]
**Describe the bug**

In README.md there is example with 
```
user := gocloak.User{
		FirstName: "Bob",
		LastName:  "Uncle",
		Email:     "something@really.wrong",
		Enabled:   true,
		Username:  "CoolGuy",
	}
```
It can't be used that way, as fields in User struct are mostly pointers

**Comment by timdrysdale** [comment]
Using the const-to-pointer helper functions this would become

```
user := gocloak.User{
	FirstName: gocloak.StringP(""Bob"),
	LastName:  gocloak.StringP(""Uncle"),
	Email:     gocloak.StringP(""something@really.wrong"),
	Enabled:   gocloak.BoolP(true),
	Username:  gocloak.StringP("CoolGuy"),
}
```
Added to [PR #240](https://github.com/Nerzal/gocloak/pull/240) seeing as that was only a README.md update.

**Comment by Nerzal** [comment]
I guess this can be closed now, as the readme.md is now fixed. Thanks @timdrysdale
