### ISSUE TITLE
DecodeAccessToken Inconsistency (Bearer keyword removal)

### ISSUE THREAD

**Issue by mirisbowring** [Nerzal/gocloak#238]
**Describe the bug**
The following function reads the keycloak authorization token (in rsa format) from header.
https://github.com/Nerzal/gocloak/blob/2abe97ee6b3036efff7611e94119f50c8fe90709/client.go#L351
First it calls the `jwx.DecodeAccessTokenHeader` function that is aware of the "Bearer" keyword in the header (it will remove it before going on).

Finally it calls `jwx.DecodeAccessToken` which is not aware of the Bearer keyword.

**Possible Solution**
Call
```go
accessToken = strings.Replace(accessToken, "Bearer ", "", 1)
```
in the mentioned function and pass the result to the header extraction and decoding at the end.

**Comment by Nerzal** [comment]
Good catch! :) 
PRs are very welcome
