### ISSUE TITLE
Plural name in client role management method

### ISSUE THREAD

**Issue by GabriFila** [Nerzal/gocloak#248]
**Is your feature request related to a problem? Please describe.**
This might be nitpicking but I would like to point it out anyway. I believe that the name for the methods 
- `AddClientRoleToUser` 
- `AddClientRoleToGroup`
- `DeleteClientRoleFromUser` 
should be 
- `AddClientRolesToUser` 
- `AddClientRolesToGroup`
- `DeleteClientRolesFromUser` 

 because they take as argument a slice of `Role` structs

**Describe the solution you'd like**
The change consists of using the plural in the name, like the method `GetClientRolesByUserID`

I'd be happy to fix it

Hope this was helpful. Thank you!

**Comment by Nerzal** [comment]
Hi, 
i understand that and agree, we can do this, but this will be a breaking change, so we'll only merge it, if we need to introduce other breaking changes :)
