### ISSUE TITLE
Support back-channel logout 

### ISSUE THREAD

**Issue by archerbj** [Nerzal/gocloak#249]
Since Keycloak supports back-channel logout by setting the admin URL of the client. Do we have some related features to support this?

**Comment by mirisbowring** [comment]
Seems like the Client Model in https://github.com/Nerzal/gocloak/blob/90cfdc90277f4e881bffd107ecb192f25acae3c6/models.go#L398 needs an additional attribute `BackChannelLogout *bool `json:"backchannelLogout,omitempty"``...

**Comment by Nerzal** [comment]
closed due to inactivity. Feel free to reopen :)
