### ISSUE TITLE
Is verification of token required / possible?

### ISSUE THREAD

**Issue by DanTulovsky** [Nerzal/gocloak#251]
Hi,

This isn't a bug, but a question. Apologies, I am just learning how this all works.  On my backend server, when it receives a token from the client (client is a CLI) which includes the bearer: <token> (this is over grpcs), I can extract data from the token like so:

```
t, claims, err := client.DecodeAccessToken(ctx, token, realm, audience)
```

Then I can check for expected values, etc.. 

Question: Is the gocloak client already doing some sort of a verification that the token was signed by the correct server, or is that something I should do myself.  If the latter, do you have any hints on how to go about doing that?  

Thank you
Dan

**Comment by DanTulovsky** [comment]
To answer my own question, gocloak.DecodeAccessToken() makes a call out to the login server to get the verification key to decode the token. It also seems to cache this.

**Comment by Nerzal** [comment]
Exactly that is the way to go :)

**Comment by Nerzal** [comment]
The returned token than has a .Valid member that is true if the token is valid :)
