### ISSUE TITLE
NewClient can not pass options

### ISSUE THREAD

**Issue by archerbj** [Nerzal/gocloak#252]
The method `NewClient` that is defined as `func NewClient(basePath string, options ...func(*gocloak)) GoCloak`, as you can see the struct `gocloak` is not exported. So IMO it is not possible to pass other options. In another word, you can pass options when calling NewClient outside of gocloak package.

```go
func getGocloakClient(options ...func(*gocloak.gocloak)) gocloak.GoCloak {
	addr :="http://localhost:8080"
	client := gocloak.NewClient(addr, options...)
	return client
}
```
the error is like 

```
/somepath/xxx.go: cannot refer to unexported name gocloak.gocloak
```

**Comment by Nerzal** [comment]
Here is a list of functional options, that you can pass into this function: 

```go
// ==== Functional Options ===

// SetAuthRealms sets the auth realm
func SetAuthRealms(url string) func(client *gocloak) {
	return func(client *gocloak) {
		client.Config.authRealms = url
	}
}

// SetAuthAdminRealms sets the auth admin realm
func SetAuthAdminRealms(url string) func(client *gocloak) {
	return func(client *gocloak) {
		client.Config.authAdminRealms = url
	}
}

// SetTokenEndpoint sets the token endpoint
func SetTokenEndpoint(url string) func(client *gocloak) {
	return func(client *gocloak) {
		client.Config.tokenEndpoint = url
	}
}

// SetLogoutEndpoint sets the logout
func SetLogoutEndpoint(url string) func(client *gocloak) {
	return func(client *gocloak) {
		client.Config.logoutEndpoint = url
	}
}

// SetOpenIDConnectEndpoint sets the logout
func SetOpenIDConnectEndpoint(url string) func(client *gocloak) {
	return func(client *gocloak) {
		client.Config.openIDConnect = url
	}
}

// SetCertCacheInvalidationTime sets the logout
func SetCertCacheInvalidationTime(duration time.Duration) func(client *gocloak) {
	return func(client *gocloak) {
		client.Config.CertsInvalidateTime = duration
	}
}
```

**Comment by archerbj** [comment]
> Here is a list of functional options, that you can pass into this function:
> 
> ```go
> // ==== Functional Options ===
> 
> // SetAuthRealms sets the auth realm
> func SetAuthRealms(url string) func(client *gocloak) {
> 	return func(client *gocloak) {
> 		client.Config.authRealms = url
> 	}
> }
> 
> // SetAuthAdminRealms sets the auth admin realm
> func SetAuthAdminRealms(url string) func(client *gocloak) {
> 	return func(client *gocloak) {
> 		client.Config.authAdminRealms = url
> 	}
> }
> 
> // SetTokenEndpoint sets the token endpoint
> func SetTokenEndpoint(url string) func(client *gocloak) {
> 	return func(client *gocloak) {
> 		client.Config.tokenEndpoint = url
> 	}
> }
> 
> // SetLogoutEndpoint sets the logout
> func SetLogoutEndpoint(url string) func(client *gocloak) {
> 	return func(client *gocloak) {
> 		client.Config.logoutEndpoint = url
> 	}
> }
> 
> // SetOpenIDConnectEndpoint sets the logout
> func SetOpenIDConnectEndpoint(url string) func(client *gocloak) {
> 	return func(client *gocloak) {
> 		client.Config.openIDConnect = url
> 	}
> }
> 
> // SetCertCacheInvalidationTime sets the logout
> func SetCertCacheInvalidationTime(duration time.Duration) func(client *gocloak) {
> 	return func(client *gocloak) {
> 		client.Config.CertsInvalidateTime = duration
> 	}
> }
> ```

Thanks, My point is if it is better to remove the variable-length parameter `options` in the `NewClient` method. Or is it reserved for future use?  anyway, thanks for the reply!

**Comment by Nerzal** [comment]
That parameter is used to not have breaking changes, when introducing new config options. 
If you do not want to set anything in there, you can just omit the parameter and the options will use default values

See Dave Cheneys great Talk about functional options:
https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

https://www.youtube.com/watch?v=24lFtGHWxAQ
