### ISSUE TITLE
Don't use pointers for maps and slices

### ISSUE THREAD

**Issue by mweibel** [Nerzal/gocloak#277]
**Describe the bug**
See #187 for a similar issue. 

Using pointers for maps and slices (e.g. `Attributes` in the `User` struct) is unnecessary and makes the library harder to use than necessary. If I saw correctly the refactoring used pointers everywhere to be able to distinguish between nil and empty values in types. Maps and slices have this feature built-in (they are [reference types](https://blog.golang.org/maps):

https://play.golang.org/p/H27ocf1bV01

Especially for maps using a pointer makes it relatively cumbersome to use:
https://play.golang.org/p/-9nbUU-PFuT

I propose, similar to the solution to #187 to get rid of pointers for reference types.

**Comment by Nerzal** [comment]
Sounds reasonable.

**Comment by mweibel** [comment]
Should I make a PR for it? 
An issue could be that you released v1 and this would be a breaking change.

**Comment by Nerzal** [comment]
A breaking change would be okay - we just increment the major version.
The benefits are bigger, than the problems that occur due to the breaking change

**Comment by mweibel** [comment]
Actually.. nevermind. I read through #174 again (properly this time) and understood the issue. Not sure if we really need pointers for maps but let's keep it that way then.
