### ISSUE TITLE
dgrijalva/jwt-go is deprecated

### ISSUE THREAD

**Issue by cameracker** [Nerzal/gocloak#292]
**Describe the bug**
dgrijalva/jwt-go is deprecated. Currently it is at use in this library at major v4.

**To Reproduce**
NA

**Expected behavior**
Packages that provide features in the authorization and authentication realm should use up to date and well maintained libraries.

Consider replacing this package with the community maintained drop in replacement: https://github.com/golang-jwt/jwt

Note: this library only has parity with dgrijalva/jwt-go@v3, it does not have any of the v4 changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/14242948/126828863-6ed0fae9-6252-4dc8-9b15-865af4cdd3fc.png)
https://github.com/dgrijalva/jwt-go#this-repository-is-no-longer-maintaned

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by Nerzal** [comment]
Good catch, thank u!

**Comment by poperor** [comment]
Another reason to address this issue is that GitHub depandbot now gives a "high severity" alert on dgrijalva/jwt-go.

**Comment by Nerzal** [comment]
do i see it correctly, that they still lack the v4 changes? 
These changes are needed to cover some features. 

I can have a deeper look later on.

**Comment by poperor** [comment]
Thaks for taking a look. Seems like dependabot gives the security alert even for v4. Any way on https://github.com/dgrijalva/jwt-go GitHub page a switch to https://github.com/golang-jwt/jwt is recommended.

**Comment by Nerzal** [comment]
I have linked a "proposal" PR

**Comment by msvechla** [comment]
Are there any updates here? With the recent CVEs in that package, I think we really should merge your proposal.

**Comment by Nerzal** [comment]
Hi, 

yes, i'll merge in the next days, as there is another possibly breaking change in the PR pipeline.
I just need to do some further testing.

**Comment by Nerzal** [comment]
Fixed in new version v10.0.1
