### ISSUE TITLE
Bad request to AddClientRoleToGroup not handled gracefully

### ISSUE THREAD

**Issue by alhague** [Nerzal/gocloak#297]
**Describe the bug**
When I make a bad request to AddClientRoleToGroup (e.g. by referencing a bad ID for the role) the keycloak server will return error 404. Gocloak (v8.5.0), however, will return error = nil

**To Reproduce**
1. Create group, client and a client role in a realm
2. Make a call to AddClientRoleToGroup where the client role does not reference a proper client role ID
3. Check the returned error

**Expected behavior**
error returned by gocloak should not be nil when there was an error

**Comment by Nerzal** [comment]
I wonder how this is even possible, as we the following function is always being executed. 

`func checkForError(resp *resty.Response, err error, errMessage string) error {
	if err != nil {
		return &APIError{
			Code:    0,
			Message: errors.Wrap(err, errMessage).Error(),
			Type:    ParseAPIErrType(err),
		}
	}

	if resp == nil {
		return &APIError{
			Message: "empty response",
			Type:    ParseAPIErrType(err),
		}
	}

	if resp.IsError() {
		var msg string

		if e, ok := resp.Error().(*HTTPErrorResponse); ok && e.NotEmpty() {
			msg = fmt.Sprintf("%s: %s", resp.Status(), e)
		} else {
			msg = resp.Status()
		}

		return &APIError{
			Code:    resp.StatusCode(),
			Message: msg,
			Type:    ParseAPIErrType(err),
		}
	}

	return nil
}`

**Comment by Nerzal** [comment]
I'll close this issue due to its age. 
If this still happens, feel free to reopen :)
