### ISSUE TITLE
Fetch authoriazation policy (resources, scope, associated policies) using keycloak policy APIs

### ISSUE THREAD

**Issue by karim-albakry** [Nerzal/gocloak#300]
**Is your feature request related to a problem? Please describe.**
As a developer i want to get the related resources, scopes, and associated policies related to a policy so that i can get the related resources of this policy

**Describe the solution you'd like**
Consume Keycloak Policy API's
1. auth/admin/realms/{realmName}/clients/{clientId}/authz/resource-server/policy/{policyId}/resources
2. auth/admin/realms/{realmName}/clients/{clientId}/authz/resource-server/policy/{policyId}/scopes
3. auth/admin/realms/{realmName}/clients/{clientId}/authz/resource-server/policy/{policyId}/associatedPolicies

**Describe alternatives you've considered**
using permission API's that provide the details of the a permission.

**Additional context**
![image](https://user-images.githubusercontent.com/25984976/130353545-a28f10d9-3204-4157-818d-5ea7e7befc23.png)

**Comment by karim-albakry** [comment]
https://github.com/Nerzal/gocloak/pull/301

**Comment by ramezmagdy** [comment]
Still not merged

**Comment by Nerzal** [comment]
it is merged now :) 
Also we have a new release
