### ISSUE TITLE
Question: How to set Scopes in the Realm?

### ISSUE THREAD

**Issue by shibumi** [Nerzal/gocloak#316]
Hello,

How would I set these Scopes via the RealmRepresentation?

![https://kurisu.shibumi.dev/share/img-2021-10-29-13-58-42.png](https://kurisu.shibumi.dev/share/img-2021-10-29-13-58-42.png)

**Comment by shibumi** [comment]
I tried setting the clientscope via filling the slice of interfaces with roles:
```go
		var scopeMappings []interface{}
		for _, scopeMapping := range *r.ScopeMappings {
			scopeMappings = append(scopeMappings, gocloak.Role{
				Name:               scopeMapping.name,
				Composite:          scopeMapping.Composite,
				ClientRole:         scopeMapping.ClientRole,
			})
		}
```

and then using this as: `scopeMappings: &scopeMappings`, but this just produces an API error. There is no documentation for setting the Scopes. Any help :(

**Comment by Nerzal** [comment]
Hi, 

i guess the best solution is to check how the Keycloak frontend sets scopes, by doing it manually while checking DevTools in the browser. That may give a hint, what we are doing wrong

**Comment by shibumi** [comment]
I fixed this. Instead of trying to writing the mappings directly into the realm I simply called these two methods here:

CreateClientScopeMappingsRealmRoles()
CreateClientScopeMappingsClientRoles()
