### ISSUE TITLE
Question: How to set password policies

### ISSUE THREAD

**Issue by shibumi** [Nerzal/gocloak#317]
Hi,

Do you know how I can set password policies? I would like to set the following policies via API:
![https://kurisu.shibumi.dev/share/img-2021-11-08-14-50-43.png](https://kurisu.shibumi.dev/share/img-2021-11-08-14-50-43.png)

But I cannot find an API function for it. There seem to be a policyRepresentation, but I have no idea how I would use this to set the policies.

**Comment by shibumi** [comment]
@bastianccm I saw your PR for this: https://github.com/Nerzal/gocloak/pull/320

Is there a list of all possible policies? How should I know that it's lowerCase(5) and not lowerCase=5 or Lowercase(5) or whatever... I am missing documentation for this to set every policy.

**Comment by bastianccm** [comment]
Hey, it's not part of gocloak, but rather how Keycloak handles this:
https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/server-spi/src/main/java/org/keycloak/models/PasswordPolicy.java#L127-L148

Essentially it is the `ID` field and the argument in brackets is whatever the `ConfigType` specifies (`int`, `none` or `String`).

**Comment by shibumi** [comment]
Hi @bastianccm not really what I was looking for, but I reverse-engineered the exact key names via the webbrowser debugging console now....

What I was looking for were the exact names for each password policy. Just for the record here are a few:

* digits(1) 
* lowerCase(1)
* upperCase(1)
* length(8)
* notUsername(undefined)
* notEmail(undefined)

**Comment by bastianccm** [comment]
Hey, jetzt, that is the names you'll get when you call the server info endpoint (my PR was related to that).
On a keycloak 15.0.2 it's http://localhost:8080/auth/admin/serverinfo
```json
[
  {
    "id": "forceExpiredPasswordChange",
    "displayName": "Expire Password",
    "configType": "String",
    "defaultValue": "365",
    "multipleSupported": false
  },
  {
    "id": "hashIterations",
    "displayName": "Hashing Iterations",
    "configType": "int",
    "defaultValue": "27500",
    "multipleSupported": false
  },
  {
    "id": "passwordHistory",
    "displayName": "Not Recently Used",
    "configType": "int",
    "defaultValue": "3",
    "multipleSupported": false
  },
  {
    "id": "passwordBlacklist",
    "displayName": "Password Blacklist",
    "configType": "String",
    "defaultValue": "",
    "multipleSupported": false
  },
  {
    "id": "length",
    "displayName": "Minimum Length",
    "configType": "int",
    "defaultValue": "8",
    "multipleSupported": false
  },
  {
    "id": "regexPattern",
    "displayName": "Regular Expression",
    "configType": "String",
    "defaultValue": "",
    "multipleSupported": true
  },
  {
    "id": "notUsername",
    "displayName": "Not Username",
    "multipleSupported": false
  },
  {
    "id": "notEmail",
    "displayName": "Not Email",
    "multipleSupported": false
  },
  {
    "id": "specialChars",
    "displayName": "Special Characters",
    "configType": "int",
    "defaultValue": "1",
    "multipleSupported": false
  },
  {
    "id": "upperCase",
    "displayName": "Uppercase Characters",
    "configType": "int",
    "defaultValue": "1",
    "multipleSupported": false
  },
  {
    "id": "lowerCase",
    "displayName": "Lowercase Characters",
    "configType": "int",
    "defaultValue": "1",
    "multipleSupported": false
  },
  {
    "id": "digits",
    "displayName": "Digits",
    "configType": "int",
    "defaultValue": "1",
    "multipleSupported": false
  },
  {
    "id": "hashAlgorithm",
    "displayName": "Hashing Algorithm",
    "configType": "String",
    "defaultValue": "pbkdf2-sha256",
    "multipleSupported": false
  },
  {
    "id": "maxLength",
    "displayName": "Maximum Length",
    "configType": "int",
    "defaultValue": "64",
    "multipleSupported": false
  }
]
```

**Comment by shibumi** [comment]
This was exactly what I am looking for. Thank you! No idea, why keycloak isn't documenting this somewhere.
