### ISSUE TITLE
Create User RealmRole assignment does not work as expected

### ISSUE THREAD

**Issue by shibumi** [Nerzal/gocloak#334]
**Describe the bug**

The RealmRoles in the User Representation are useless when creating a new user.

**To Reproduce**

Create a new user via the CreateUser() call and set the []string value of RealmRoles to prior created roles.
I tried using the roleNames: for example "admin", "operator" and I tried using the roles ID (get via GetRealmRole).
But do not work.

**Expected behavior**
CreateUser() should create RealmRole assignments OR it should be documented that this value is read-only and not intended for write operations.

**Additional context**
Tested with keycloak version: quay.io/keycloak/keycloak:15.0.2
And:  github.com/Nerzal/gocloak/v9 v9.0.4

**Comment by Nerzal** [comment]
The behavior is also not documented in the Keycloak REST API, that this client is using.
