### ISSUE TITLE
Endpoint login has change without /auth

### ISSUE THREAD

**Issue by panjisadewo** [Nerzal/gocloak#341]
**Describe the bug**
Endpoint login has change

Hi Nerzal i found a bug keycloack 17 endpoint login is change

Regards
Thanks

**Comment by gdalfovo** [comment]
I confirmed

**Comment by d-kononov** [comment]
As a quick fix use: `gocloak.NewClient("some-base-path", gocloak.SetAuthRealms("realms"), gocloak.SetAuthAdminRealms("admin/realms"))`

**Comment by Nerzal** [comment]
Hi everyone, what exactly has changed? 
We might need to introduce some kind of version switch, if keycloak changed the URLs

**Comment by d-kononov** [comment]
Default path for v16 is `/auth/...`
Default path for v17 is `/...`

**Comment by Shimazu1** [comment]
I think it would be a good idea to use the .well-known endpoint of Keycloak to get endpoints where it is possible, so if there are further changes to the path, gocloak is not affected

**Comment by bovinemagnet** [comment]
Doesn't the change only affect Keycloak 17 running on Quarkus ? (which is now the default distribution)

But if you are still running on WildFly, then the `auth` path still remains ?

**Comment by Nerzal** [comment]
> I think it would be a good idea to use the .well-known endpoint of Keycloak to get endpoints where it is possible, so if there are further changes to the path, gocloak is not affected

Yes! This is a good solution

**Comment by mbecker** [comment]
Hi,

in the meantime set as described above the endpoint's paths as follows: [https://github.com/Nerzal/gocloak/issues/346#issuecomment-1087955684](https://github.com/Nerzal/gocloak/issues/346#issuecomment-1087955684)
