### ISSUE TITLE
Create mapper for Client or Client Scopes

### ISSUE THREAD

**Issue by ognjen-it** [Nerzal/gocloak#345]
**Describe the bug**
We cannot create a mapper for Client or Client Scopes

**To Reproduce**

```
var (
    ognjenGlobalName         = flag.String("ognjenGlobalName", "ognjen", "")
    ognjenClientProtocol     = flag.String("ognjenClientProtocol", "openid-connect", "")
    ognjenProtocolMapperName = flag.String("ognjenProtocolMapperName", "User Realm Role", "")
    ognjenGlobalOn           = flag.String("ognjenGlobalOn", "on", "")
)

func createClientScopeOgnjen() {

	ognjenClientScope := gocloak.ClientScope{
		Name:        ognjenGlobalName,
		Description: ognjenGlobalName,
		Protocol:    ognjenClientProtocol,
		ProtocolMappers: &[]gocloak.ProtocolMappers{
			{
				Name:           ognjenGlobalName,
				Protocol:       ognjenClientProtocol,
				ProtocolMapper: ognjenProtocolMapperName,
				ProtocolMappersConfig:  &gocloak.ProtocolMappersConfig{
					UserinfoTokenClaim: ognjenGlobalOn,
					IDTokenClaim:       ognjenGlobalOn,
				},
			},
		},
	}

	inf, err := client.CreateClientScope(ctx, token.AccessToken, *ognjenGlobalName, ognjenClientScope)
	if err != nil {
		fmt.Print(err.Error())
	} else {
		fmt.Print(inf)

	}
}
```

**Expected behavior**
We want to create a Client Scope with a special mapper

**Screenshots**
With the above code, we can create a Client Scope but a mapper has not been created.
<img width="873" alt="image" src="https://user-images.githubusercontent.com/44586606/159511798-f17c290f-2582-4c69-b5d7-928ccfd0d089.png">

**Additional context**
Keycloak version is 16.1.1, it's deployed with helm on Kubernetes 1.21
I didn't find any example of how to do it :(

**Comment by HimanshuM** [comment]
@ognjen-it could you tell us why you closed this issue? I am facing the same issue, but could not find a solution in the package.

**Comment by ognjen-it** [comment]
because I don't think there are people here who are willing to help.. :(
However, I will reopen it :)

**Comment by HimanshuM** [comment]
Thanks for your response @ognjen-it . I have created a PR for this issue https://github.com/Nerzal/gocloak/pull/351

**Comment by ognjen-it** [comment]
Wow, great to know that 🤗
Thank you for your effort to do that 🎉💯

I would like to know how to improve the gocloak, but I don't know the go language very well...

**Comment by HimanshuM** [comment]
Hey @ognjen-it the PR is now merged. Once a release is created, you could update the package and try it out.
Thanks for your support :)

**Comment by ognjen-it** [comment]
Great! Thank you very much 🚀💯🥇
I will check it now and confirm if we can close this issue :)

**Comment by ognjen-it** [comment]
Yes, you can  :)
Thank all!

**Comment by chsavvaidis** [comment]
@Nerzal  @ognjen-it  Hey, I am facing the same issue in both V11.1.0  and V11.2.0 :)
