### ISSUE TITLE
gocloak is broken for Keycloak v17.0 : need to remove /auth from the gocloak endpoint path

### ISSUE THREAD

**Issue by ksingh7** [Nerzal/gocloak#346]
**Describe the bug**
Upon hitting any of the API calls i am getting error

```
404 Not Found: RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/realms/dev/protocol/openid-connect/token
```

**To Reproduce**
1. Keycloak Version `17.0.1`
2. gocloak version `11.0.2`
3. Hit the gocloak api (any method)
```
jwt, err := keycloakClient.Login(
		kCTX,
		kCreds.clientId,
		kCreds.clientSecret, kCreds.realm,
		kCreds.username, kCreds.password,
	)
```
FYI direct CURL on keyckoak works fine

![image](https://user-images.githubusercontent.com/9701902/160430544-ca9d9e1f-c674-449b-8bdc-ef0b651d8aba.png)

**Expected behavior**
We should able to successfully authenticatae using gocloak method 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**
Important : Starting 17.0+ version of Keycloak, there's a change in endpoints as per the [official documentation](https://www.keycloak.org/docs-api/11.0/rest-api/index.html#_users_resource), you need to omit `/auth` from the endpoint. 
We need a mechanism in gocloak to omit `\admin`

**Comment by ksingh7** [comment]
@Nerzal  i would like to thank you for this wonderful Go Library. With this bug i wanted to bring it to your notice that `gocloak` endpoints are broken with latest version of keycloak (17.0). gocloak API uses an additional `\auth` in the route path that needs to be omited in order for it to work with keycloak v 17.0

**Comment by ksingh7** [comment]
More Info https://keycloak.discourse.group/t/using-curl-or-postman-results-in-could-not-find-resource-for-full-path/13638

**Comment by mbecker** [comment]
Hi,

see [https://github.com/Nerzal/gocloak/issues/252](https://github.com/Nerzal/gocloak/issues/252) how to change the endpoint`s paths.

Fully example for Keycloak 17:

```go
package main

import (
	"context"
	"crypto/tls"
	"fmt"

	gocloak "github.com/Nerzal/gocloak/v11"
)

var URL string = "https://127.0.0.1:8443"

func main() {

	realm := "master"
	clientID := "my-resource-server"
	clientSecret := "***"

	client := gocloak.NewClient(URL, gocloak.SetAuthAdminRealms("admin/realms"), gocloak.SetAuthRealms("realms"))
	restyClient := client.RestyClient()
	restyClient.SetDebug(true)
	restyClient.SetTLSClientConfig(&tls.Config{InsecureSkipVerify: true})
	ctx := context.Background()
	token, err := client.LoginClient(ctx, clientID, clientSecret, realm)
	if err != nil {
		panic("Login failed:" + err.Error())
	}
	fmt.Println(token)
}
```

**Comment by Howard3** [comment]
thanks @mbecker I can confirm this works.

**Comment by burner-account** [comment]
The problem is a bit more complicated.

Keycloak dropped the default /auth prefix, but supports path prefixes. (see `KC_HTTP_RELATIVE_PATH` in build, `--hostname-path` in configuration)

I for myself have to keep the previously used /auth prefix and therefore cannot support the "just remove it" approach.

**Comment by maitredede** [comment]
Hi,

I am using Keycloak 18 with lib v11.1.0. I have updated the options for the path change. The `GetUserInfo` works, but not the `GetServerInfo` : still 404. The source code shows hardcoded `"auth"` in `makeURL` call :smile:

**Comment by tjarkmeyer** [comment]
I found this in the migrating to quarkus guide:

**Default context path changed**
By default, the new Quarkus distribution removes /auth from the context-path. To re-introduce the /auth use the [http-relative-path](https://www.keycloak.org/server/all-config?q=http-relative-path&f=build) build option. For example:

`bin/kc.[sh|bat] start-dev --http-relative-path /auth`

https://www.keycloak.org/migration/migrating-to-quarkus

**Comment by ricardogayer** [comment]
Thanks [mbecker](https://github.com/mbecker) for share this solutions!

**Comment by Nerzal** [comment]
We've created a ticket to address this problem at my workplace. 
This will be resolved soon :)
