### ISSUE TITLE
Request to support authentication and additional client context for gocloak.CreateClientRepresentation

### ISSUE THREAD

**Issue by tarvitz** [Nerzal/gocloak#358]
**Is your feature request related to a problem? Please describe.**
gocloak.CreateClientRepresentation might require auth-n/z and provided gocloak.Client (client-id, scopes, etc) to be able to create properly configured representation.

I've tried to use the latest gocloak (v11) to operate with client representations like it was described in #304 as an issue. It works like expected for retrieve, delete(revoke) operations. However, as our keycloak server requires authentication/authorization to create new representations, and the current way to perform it using gocloak leads to a failure (401 unauthorized).

**Describe the solution you'd like**
Be able to pass authentication context (e.g. use somehow getRequestWithBearerAuth) and newClient (gocloak.Client) resource.
```go
if newClient, err := keycloak.CreateClientRepresentation(
		context.TODO(), command.jwt.AccessToken, command.Realm,
		command.NewClient(clientID)); err == nil {
		command.Print(newClient, o.NewFormatter("{{ .AccessToken }}\n"))
}
```

**Describe alternatives you've considered**
Use our own CreateClientRepresentation with the following contents:
```go
// CreateClientRepresentation creates a new client representation
func (client *gocloak) CreateClientRepresentation(ctx context.Context, token, realm string, newClient Client) (*Client, error) {
	const errMessage = "could not create client representation"

	var result Client
	resp, err := client.getRequestWithBearerAuth(ctx, token).
		SetResult(&result).
		SetBody(&newClient).
		Post(client.getRealmURL(realm, "clients-registrations", "default"))

	if err := checkForError(resp, err, errMessage); err != nil {
		return nil, err
	}

	return &result, nil
}
```

**Additional context**
Related to issue #304.
Unfortunately I didn't manage how to run tests and make them work, but these changes worked for me (https://github.com/Nerzal/gocloak/commit/fc08ecff3644d2b6a6e3c206e2e5b04ad450886a)

**Comment by Nerzal** [comment]
Hi, 

i'm currently working on a new release. 
That will also include the fix for this issue. 

The current progress is on the dev branch.
