### ISSUE TITLE
Question: Check if user has access to client resource 

### ISSUE THREAD

**Issue by skast96** [Nerzal/gocloak#364]
Hi,

is there a way to check if a user with a token has access to a resource. For example: 

![image](https://user-images.githubusercontent.com/10941954/188465802-b4773526-a02f-404a-baa9-e10ebc76890d.png)

I have a resource called "user" with the URI /api/user and I want to check if a user can access it, or if he should be blocked with an access denied error. 

It already works in the evaluate tab, but I could not figure it out how it works with the library.

**Comment by skast96** [comment]
Figured it out myself. 
 1. Request a clients resources by calling GetResourcesClient with the uri of a resource (/api/device/create) and a client token
 2. Request permissions for a user token with GetRequestingPartyPermissions
 3. Check if the resulting resourceId of step 1 is inside the permissions array of step 2.

**Comment by Kowiste** [comment]
Hi @skast96, I know is a lot of time ago, I'm trying to do what you say 

```
	userToken := c.Request.Header.Get("Authorization")[7:]

	token, claims, err := s.client.DecodeAccessToken(context.Background(), userToken, ActiveRealm)
	if err != nil {
		c.AbortWithStatusJSON(http.StatusUnauthorized, err)
		return
	}
	if !token.Valid {
		c.AbortWithStatusJSON(http.StatusUnauthorized, err)
		return
	}
	fmt.Println(claims, token)
	resources, err := s.client.GetResourcesClient(s.kcContext, s.token.AccessToken, ActiveRealm, gocloak.GetResourceParams{})
	if err != nil {
		c.AbortWithStatusJSON(http.StatusUnauthorized, err)
		return
	}
	fmt.Println(resources)
	permissions, err := s.client.GetRequestingPartyPermissions(s.kcContext, userToken, ActiveRealm, gocloak.RequestingPartyTokenOptions{})
	if err != nil {
		c.AbortWithStatusJSON(http.StatusUnauthorized, err)
		return
	}
	fmt.Println(permissions)
	for _, permission := range *permissions {
		for _, resource := range resources {
			if permission.ResourceID == resource.ID {
				c.Next()
				return
			}
		}

	}
	c.AbortWithError(http.StatusUnauthorized, errors.New("not authorize"))
```
GetRequestingPartyPermissions give me the follow error

```
{
    "code": 400,
    "message": "400 Bad Request: invalid_request: You must provide the issuedFor",
    "type": "unknown"
}
```
Do you know what I'm doing wrong, could you post your code?

**Comment by skast96** [comment]
Sure! Instead of `GetRequestingPartyPermissions` I am using the `GetRequestingPartyPermissionDecision` like: 
```
permissions := []string{resourceId}
perms, err := cloak.Gocloak.GetRequestingPartyPermissionDecision(context.Background(), userToken, cloak.Realm, gocloak.RequestingPartyTokenOptions{Audience: &cloak.ClientId, Permissions: &permissions})

if err != nil {
	if apiErr, ok := err.(*gocloak.APIError); ok {
		if apiErr.Code == http.StatusForbidden {
			return false, nil
		}
        }
		return false, echo.ErrInternalServerError
}
return *perms.Result, nil
```

This checks the permission directly for a given resourceId which you also get from the `GetResourcesClient` function.

**Comment by mzcoder-hub** [comment]
> Hi,
> 
> is there a way to check if a user with a token has access to a resource. For example:
> 
> ![image](https://user-images.githubusercontent.com/10941954/188465802-b4773526-a02f-404a-baa9-e10ebc76890d.png)
> 
> I have a resource called "user" with the URI /api/user and I want to check if a user can access it, or if he should be blocked with an access denied error.
> 
> It already works in the evaluate tab, but I could not figure it out how it works with the library.

its been a long time, but where is the Feature on the image of youre ini the current version ?
