### ISSUE TITLE
Help with example of how to create a group with assigned roles

### ISSUE THREAD

**Issue by dthisner** [Nerzal/gocloak#370]
I do not really understand how I am suppose to add roles onto a group when I am creating it. Looking at the **Group** struct, it is showing a map of array. When assigning roles to user, they are using specific role groups to assign to the user **gocloak.Role**

What I currently have: 
```go
	group := gocloak.Group{
		Name: &name,
	}

	if len(role) != 0 {
		roles := strings.Split(role, ",")

		if !check.Roles(roles) {
			return fmt.Errorf("please provide correct roles! ex: \"admin\" or \"licensed_user\". You provided \"%v\"", roles)
		}

		clientRoles := map[string][]string{}
		clientRoles["client_role"] = roles
		group.ClientRoles = &clientRoles
	}

	client.CreateGroup(ctx, token.AccessToken, "dash", group)
```

It creates the group, does not assign the roles. 

I assume that the map is working as: 
```go
map[<The Client Role>][]string{<The roles that you want to get from the client role>}
```

**Comment by bastianccm** [comment]
Hi @dthisner ,

gocloak is pretty "low-level" and directly uses the Keycloak admin API, which does not assign roles when a group is created (even though the models would allow this).
Therefore you need to create the group and roles, and afterwards use `client.AddClientRoleToGroup`:
```go
group := gocloak.Group{
	Name: &name,
}

// this will be a parameter or something
// roles always need name _and_ id, as keycloak requires that both are set.
roles := []gocloak.Role{
	{Name: gocloak.StringP("role-1"), ID: gocloak.StringP("id-of-role-1")},
	{Name: gocloak.StringP("role-2"), ID: gocloak.StringP("id-of-role-2")},
}

if len(roles) > 0 {
	if !check.Roles(roles) {
		return fmt.Errorf("please provide correct roles! ex: \"admin\" or \"licensed_user\". You provided \"%v\"", roles)
	}
}

client.CreateGroup(ctx, token.AccessToken, "dash", group)

if len(roles) > 0 {
	client.AddClientRoleToGroup(ctx, token.AccessToken, "dash", "client_role", roles)
}
```
Reference in keycloak:
https://github.com/keycloak/keycloak/blob/42ad95af4d592c4b9c35ff56fcd1454ceeec6198/services/src/main/java/org/keycloak/services/resources/admin/ClientRoleMappingsResource.java#L152-L159

**Comment by dthisner** [comment]
Thank you very much for helping out and with a quick response :) much appreciated!

**Comment by hamzaachi** [comment]
Hi,

I am trying to use the example above to assign roles to a groups but it is not working for me. It complains the roles are nil:
```

roles := []gocloak.Role{
		{Name: gocloak.StringP("role-1"), ID: gocloak.StringP("id-of-role-1")},
		{Name: gocloak.StringP("role-2"), ID: gocloak.StringP("id-of-role-2")},
	}
	fmt.Println("Roles: ", roles)
	err := target.AddClientRolesToGroup(ctx, token, c.Kc_target.Realm, "MyClientID", *Group.ID, roles)
	if err != nil {
		return fmt.Errorf("Cannot Add Roles To Group Error: %s", err.Error())
	}
```
Output:

Roles:  [{0xc0002aa990 0xc0002aa980 <nil> <nil> null <nil> <nil> <nil> <nil>} {0xc0002aa9b0 0xc0002aa9a0 <nil> <nil> null <nil> <nil> <nil> <nil>}]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6b6831]

goroutine 1 [running]:
main.(*Instance).AddGroup(0xc0000c5ef8, {0x7cdff0, 0xc000098000}, {0xc0002b2400, 0x3d7}, 0xc000098b40?, 0xc000192100)
        /home/hachi/MyDATA/eadn/Projects/Programming/Go/kc/kc_ops.go:150 +0x231
main.Kc_AddGroups({0x7cdff0, 0xc000098000}, {0xc0000cc7e0}, 0x0?, 0x73f9d7?)
        /home/hachi/MyDATA/eadn/Projects/Programming/Go/kc/main.go:99 +0x316
main.main()


Any clue ?
Thanks

**Comment by hamzaachi** [comment]
@bastianccm can you help please ?

**Comment by hamzaachi** [comment]
My bad *Group.ID was nil
