### ISSUE TITLE
Front end url 

### ISSUE THREAD

**Issue by Kowiste** [Nerzal/gocloak#377]
Hi I'm using Keycloak inside a container and it send a registration email, when the email arrive the url is the name of the container.

I was looking but cant find the way to modify that. There is any way to do this?

**Comment by Nerzal** [comment]
Hi, 
Keycloak behaves pretty strange with these e-mails. 
The Host-URL used is always the host url, that the client used to authenticated with keycloak.

If you want the E-Mail to have some public facing URL, you need to use this public URL in the gocloak client when authenticating and triggering mails.
