### ISSUE TITLE
[Question] Which Keyloak version that `gocloak` support ? 

### ISSUE THREAD

**Issue by wavemoroc001** [Nerzal/gocloak#389]

**Comment by Nerzal** [comment]
Gocloak V12 should support keycloak until atleast v19.0.0 
Not tested with keycloak v20.0.0 yet, but i guess it will work. 

Gocloak <=V11 supports keycloak until ~17 (i guess)

**Comment by wavemoroc001** [comment]
@Nerzal This will support keycloak v.20 ?

**Comment by r3st** [comment]
I'm working with gocloak v12 and use keycloak v15.1.1 and v20.0.0.
