### ISSUE TITLE
Adding and deleting client-level roles to the user role mapping

### ISSUE THREAD

**Issue by chrnin** [Nerzal/gocloak#74]
Hi,

I'm using gocloak to automate user management in keycloak, and I need to manage client roles for my users. I tried to use the AddRealmRoleToUser and DeleteRealmRoleFromUser functions with my client roles in the input parameters, but I get a 404 error (that's pretty predictable). Therefore I didn't find any methods in the gocloak package that handled these two methods.

API endpoints are described here: https://www.keycloak.org/docs-api/2.5/rest-api/index.html#_delete_client_level_roles_from_user_role_mapping_2

Actually, what I need is AddClientRoleToUser and DeleteClientRoleFromUser functions pointing to these methods' endpoints.

I'm thinking of adding theses functions on my own because I don't have much time to make it happen, maybe this is already possible and I didn't find how to do it ? So Before I start coding this on my side, I ask it here :)

Thanks !

Christophe.

**Comment by SVilgelm** [comment]
Hi @chrnin, We already had this question in slack:
```
Sergey Vilgelm [12:38 PM]
@Surya Penmetcha There is a function GetRoleMappingByUserID it returns also client roles for user
user has a client role test-gocloak-client-role 

  client_test.go:1305: {
     "clientMappings": {
      "account": {
       "id": "0840c234-5b67-41f2-b001-415edf769bc3",
       "client": "account",
Click to expand inline (52 lines)

Sergey Vilgelm [12:45 PM]
Also there is an API to add and delete client roles to a User: https://www.keycloak.org/docs-api/6.0/rest-api/index.html#_client_role_mappings_resource
• Add client-level roles to the user role mapping: `POST /{realm}/users/{id}/role-mappings/clients/{client}`
• Delete client-level roles from user role mapping: `DELETE /{realm}/users/{id}/role-mappings/clients/{client}`
But this API is not implemented yet, so you will need to do it your-self
```

If you have a time, please send a Pull Request. It's really easy to implement the functions

**Comment by SVilgelm** [comment]
I probably will have a time on this week, but cannot guaranty

**Comment by chrnin** [comment]
I'm already looking how it's done and I think I'll can do it without breaking everything ! I'll probably send a PR ! Thanks for your quick answer !

**Comment by SVilgelm** [comment]
Release: https://github.com/Nerzal/gocloak/releases/tag/v3.7.0
