### ISSUE TITLE
omitempty string attributes break when empty

### ISSUE THREAD

**Issue by Teelevision** [Nerzal/gocloak#79]
**Describe the bug**
Setting an user's `Email` attribute to an empty string and updating the user does not actually remove the user's email address. The same goes for basically every string attribute.

**To Reproduce**
1. Create user with an email address in Keycloak Admin Console.
2. Query that user using gocloak (`GetUserByID()`).
3. Set `user.Email = ""`
4. `UpdateUser()`
5. Observe in the Keycloak Admin Console that the user still has the email address.

**Expected behavior**
The user's email address is removed. This is expected behavior as this works if you delete the email address in the Keycloak Admin Console.

**Additional context**
Probably all string attributes (and possibly other attributes as well) should not have the json `omitempty` tag.
[This was already addressed](https://github.com/Nerzal/gocloak/issues/59) and [removed for bool attributes](https://github.com/Nerzal/gocloak/commit/031e3bae86a01af26aaa06ff1b2f0370769f93a3).

**Comment by SVilgelm** [comment]
There is a huge problem, we were able to do it with bool attributes, because there are not so much, but with string attributes it will not work, because if we are going to update a user's first name then we must to set same email, otherwise it will be set to empty. There is only one way how to fix this problem - using pointers for all attributes.
@Nerzal ^^^

**Comment by Nerzal** [comment]
Aaaarghs not again

**Comment by SVilgelm** [comment]
I have a couple ideas how to fix this problem:
1. Using only pointers
2. Having two copies of representations: the first (with pointers) for requests and the second (no pointers) for responses

**Comment by Nerzal** [comment]
Another option would be implementing a custom json serializer for this struct.

**Comment by SVilgelm** [comment]
That is possible too, but how are you going to determine that the email attribute is empty or is not set?

**Comment by SVilgelm** [comment]
Also we can use setters and getters: https://play.golang.org/p/PxZ_gObjPlf

**Comment by SVilgelm** [comment]
As far as I can see, many libraries use pointers, take a look at the go-github: https://github.com/google/go-github/blob/master/github/users.go

**Comment by Nerzal** [comment]
Okay so we have some options.

What would be best for usability ? 
And what would be the best for maintainability?

My guess is the option to have 1 private struct for for requests and 1 public for responses which we give out to consumers of the library. But that would be not as maintainable as only having 1 struct.

**Comment by dcarbone** [comment]
fwiw i have been down this path several times and ultimately the easiest to understand and use is to simply use pointers for all fields.

trying to get overly creative with solutions here just results in easy points of failure and forgetfulness as to how / why the cleverness works / worked.

**Comment by SVilgelm** [comment]
@dcarbone thank you so much.
So let's do the pointers.
