### ISSUE TITLE
Get Client Service Accounts

### ISSUE THREAD

**Issue by kisamoto** [Nerzal/gocloak#86]
**Is your feature request related to a problem? Please describe.**
Functionality to retrieve Service Account UserRepresentation for a Client: https://www.keycloak.org/docs-api/6.0/rest-api/index.html#_getserviceaccountuser

**Describe the solution you'd like**
Method to retrieve a Service Account for a Client

**Describe alternatives you've considered**
Manual API call

**Comment by Nerzal** [comment]
Fixed with #87
