### ISSUE TITLE
Not able to LoginClient

### ISSUE THREAD

**Issue by soamyak** [Nerzal/gocloak#88]
My keyclaok instance is set up in a corporate network and I am successfully able to generate token in POSTMAN but I am facing issue while handling it in my golang API.

	client := gocloak.NewClient("https://keycloakt.iservice..corporateserver/auth/realms/i-service/protocol/openid-connect/auth")
	clientID := "test-data"
	clientSecret := "11550ca3-2437-451f-b66e-80bdf9dd8a5a"
	realm := "I-service"
	token, err := client.LoginClient(clientID, clientSecret, realm)
	if err != nil {
		panic("Login failed:" + err.Error())
	}

On run, its give panic saying - Login failed:404 not found. 

'To configure client, I tried the access token URL as well as the issuer URL for keycloak client but in every case it gives Login failed:404 not found. 

Is your library needs any proxy details to connect to keycloak server ?

**Comment by Nerzal** [comment]
https://keycloakt.iservice..corporateserver/auth/realms/i-service/protocol/openid-connect/auth

The URL is your problem. You only need to set the base path to your keycloak instance.

Like: https://my-keycloakinstance.com

That should do the trick.

**Comment by soamyak** [comment]
Yes, it did the trick :) 

Though I am getting null response from my API call irrespective of passing correct AccessToken and Incorrect AccesToken from POSTMAN.

http://localhost:5000/v1.0/testplans?group=TEST&name=TEST. 

My call back URL configured in my keycloak client is - http://localhost:5000/v1.0 and,
I am using Grant Type - Client Credentials to generate access token from POSTMAN end.

Does the RetrospectToken function supports all type of grant type?

**Comment by soamyak** [comment]
I am not getting any error on Login and Retrospect function, but what I  don't understand is how it is validating the accesstoken from the header of request? As Retrospect function uses -token.AccessToken from keycloak client while it is login. 

token, err := client.LoginClient(clientID, clientSecret, realm)
client.RetrospectToken(token.AccessToken, clientID, clientSecret, realm)

I am not sure how to do a negative test, as irrespective of whether we are sending accesstoken in request header or not, it would still run as it is generating the token everytime it is run ?
