### ISSUE TITLE
how to implement authorization functions?

### ISSUE THREAD

**Issue by shidongjian** [Nerzal/gocloak#95]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SVilgelm** [comment]
Do you still need help? Could you add more details, what do you want to implement? If you want to authorize in the key cloak, you can find an example of this in the `client_test.go` file.

**Comment by SVilgelm** [comment]
I'm closing it
