### ISSUE TITLE
Client.BaseURL JSON mapping has incorrect case

### ISSUE THREAD

**Issue by kfiles** [Nerzal/gocloak#96]
**Describe the bug**
When updating a Keycloak ClientRepresentation which contains a baseUrl field via UpdateClient, Keycloak responds with a 400 Bad Request: "Unrecognized field "baseURL" (class org.keycloak.representations.idm.ClientRepresentation), not marked as ignorable"

This is because the JSON mapping of Client.BaseURL has the incorrect case `baseURL`, rather than the expected `baseUrl` for the Keycloak API.

We are using Keycloak 7.0.

**To Reproduce**
1. In Keycloak, create a Client, and set a Base URL.
2. Execute the following code:
```
	client := gocloak.NewClient(conf.Server)
	token, err := client.Login(conf.AdminClientID, conf.AdminClientSecret, conf.AdminRealm, conf.AdminUser, conf.AdminPassword)
	if err != nil {
		err = errors.Wrap(err, "Something wrong with the credentials or url")
		return err
	}
	params := gocloak.GetClientsParams{
		ClientID:    clientID,
		ViewableOnly: false,
	}
        //Find the client you've created, with the given clientId
	appClients, err := client.GetClients(token.AccessToken, realm, params)

	if err != nil {
		err = errors.Wrapf(err, "Couldn't get client with id %v", clientID)
		return err
	}
	appClient := appClients[0]
	body, err := json.Marshal(*appClient)
	klog.V(2).Infof("Client Body:\n%v", string(body))
	err = client.UpdateClient(token.AccessToken, realm, *appClient)
	if err != nil {
		err = errors.Wrapf(err, "Failure updating client")
			return err
	}
```
3. Get 400 error

**Expected behavior**
UpdateClient should PUT a well-formed ClientRepresentation JSON object and receive a 200 response.

**Comment by SVilgelm** [comment]
Hi,
it's already fixed in #94, we just need to create a new tag or you can use master

**Comment by SVilgelm** [comment]
Here it is https://github.com/Nerzal/gocloak/releases/tag/v3.5.1

**Comment by kfiles** [comment]
Thanks a lot. Works great.
